import "./ditto.css";
import FeatureCard from "./components/feature-card";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const FeatureCard_data = [
  { title: "PREP", description: "Comprehensive planning, concept art, and pre-visualization to set the vision." },
  { title: "Story Board", description: "Translating scripts into detailed sequential art for precise camera and scene planning." },
  { title: "Story Telling", description: "Crafting compelling narratives through visual cues, pacing, and dynamic frame composition." },
  { title: "CGI Production", description: "High-fidelity 3D modeling, texturing, rigging and character animation for films and digital platforms." },
  { title: "Motion Graphics", description: "Futuristic UI design, kinetic titles, corporate brand reels and visual graphic projections." },
  { title: "3D Animation", description: "Full-character animation, complex mechanical rigs and stylized environmental narratives." },
  { title: "Compositing", description: "Seamlessly stitching greenscreen footage, live plates, matte paintings, and 3D assets." },
  { title: "ROTO", description: "High-precision edge matte creation, paint fixes, wire removals and plate reconstructions." },
  { title: "Matchmove", description: "Pixel-perfect 3D camera tracking, object tracking, and lens distortion calibrations." },
  { title: "Color Grading", description: "Stunning cinematic color correction and grade passes that elevate visual storytelling." },
  { title: "Digital Cleanup", description: "Removing unwanted artifacts, structural repairs, rig removals and cosmetic cleanups." }
];
const ListRow_data = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/works", label: "Our Works" },
  { href: "/career", label: "Careers" },
  { href: "/contact", label: "Contact Us" }
];
const ListRow2_data = [
  { label: "PREP" },
  { label: "Story Board" },
  { label: "Story Telling" },
  { label: "CGI Production" },
  { label: "Motion Graphics" },
  { label: "3D Animation" },
  { label: "Compositing" },
  { label: "ROTO" },
  { label: "Matchmovie" },
  { label: "Colour Grading" },
  { label: "Digital Cleanup" }
];
const FeatureCard_cids: string[][] = [
  ["n72", "n73", "n74", "n75", "n76"],
  ["n77", "n78", "n79", "n80", "n81"],
  ["n82", "n83", "n84", "n85", "n86"],
  ["n87", "n88", "n89", "n90", "n91"],
  ["n92", "n93", "n94", "n95", "n96"],
  ["n97", "n98", "n99", "n100", "n101"],
  ["n102", "n103", "n104", "n105", "n106"],
  ["n107", "n108", "n109", "n110", "n111"],
  ["n112", "n113", "n114", "n115", "n116"],
  ["n117", "n118", "n119", "n120", "n121"],
  ["n122", "n123", "n124", "n125", "n126"]
];
const ListRow_cids: string[][] = [
  ["n151", "n152"],
  ["n153", "n154"],
  ["n155", "n156"],
  ["n157", "n158"],
  ["n159", "n160"]
];
const ListRow2_cids: string[][] = [
  ["n164", "n165"],
  ["n166", "n167"],
  ["n168", "n169"],
  ["n170", "n171"],
  ["n172", "n173"],
  ["n174", "n175"],
  ["n176", "n177"],
  ["n178", "n179"],
  ["n180", "n181"],
  ["n182", "n183"],
  ["n184", "n185"]
];
const FeatureCard_styles = [
  { className: "before:bottom-[13.4125rem] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[237.1px] md:max-lg:before:bottom-[13.4125rem]", className2: "before:content-['']" },
  { className: "before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" },
  { className: "before:bottom-[13.4125rem] max-md:before:bottom-[237.1px] md:max-lg:before:bottom-48", className2: "before:content-['']" }
];

export default function Page() {
  return (
    <>
      <section className="h-170 min-h-170 flex relative pt-20 items-center overflow-hidden bg-background max-md:h-[43.1375rem] max-md:min-h-[43.1375rem] md:max-lg:h-[54.4rem] md:max-lg:min-h-[54.4rem] 2xl:h-229.5 2xl:min-h-229.5" data-cid="n22">
        <div className="h-full block absolute top-0 inset-x-0 z-0 min-w-0" data-cid="n23">
          <div className="w-320 h-170 block absolute top-0 left-0 bg-cover [background-position:50%_0%] [filter:grayscale(0.8)_brightness(0.3)_contrast(1.2)] [animation-name:bgSlowZoom] [animation-duration:12s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] [animation-direction:alternate] max-md:w-[23.4375rem] max-md:h-[43.1375rem] md:max-lg:w-192 md:max-lg:h-[54.4rem] 2xl:w-480 2xl:h-229.5" style={{ backgroundImage: "url(\"/assets/cloned/images/46fe0eb562c1.jpg\")" }} data-cid="n24" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 z-1" style={{ backgroundImage: "linear-gradient(135deg, var(--clr-6) 0%, var(--clr-12) 60%, var(--clr-2) 100%)" }} data-cid="n25" />
          {" "}
          <div className="w-125 h-125 block absolute -top-17 -left-32 z-2 opacity-[0.66568] [mix-blend-mode:screen] [filter:blur(60px)] [animation-name:volumetricPulse] [animation-duration:6s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] pointer-events-none max-md:-top-[4.3125rem] max-md:left-[-37.5px] md:max-lg:-top-[5.4375rem] md:max-lg:-left-[4.8rem] 2xl:-top-[5.7375rem] 2xl:-left-48" style={{ backgroundImage: "radial-gradient(at 70% 40%, var(--clr-26) 0%, var(--clr-4) 55%)" }} data-cid="n26" />
          {" "}
          <img className="w-320 h-170 block absolute z-3 overflow-clip aspect-[auto_1280/680] pointer-events-none max-md:w-[23.4375rem] max-md:h-172.5 max-md:aspect-[auto_375/690] md:max-lg:w-192 md:max-lg:h-217.5 md:max-lg:aspect-[auto_768/870] 2xl:w-480 2xl:h-229.5 2xl:aspect-[auto_1920/918]" data-cid="n27" height="680" id="hero-particles" src="/assets/cloned/images/56ea4cef4caa.png" width="1280" alt="" />
          {" "}
        </div>
        {" "}
        <div className="block relative z-10 max-w-320 mx-[7.9375rem] py-16 px-8 text-left max-lg:max-w-full max-md:mx-0 md:max-lg:mx-[1.6875rem] 2xl:mx-[23.1125rem]" data-cid="n28">
          <span className="border border-solid border-color-006 inline-block mb-6 py-[0.4rem] px-4 rounded-[50px] text-primary [font-family:Outfit,_sans-serif] text-xs font-bold leading-[0.9375rem] tracking-[3.46px] uppercase" data-cid="n29">
            FOCUS VFX STUDIO — ABOUT US
          </span>
          {" "}
          <h1 className="block mb-6 text-[5.625rem] font-black leading-[5.3125rem] tracking-[-1.79px] uppercase max-md:text-5xl max-md:leading-[2.875rem] max-md:tracking-[-0.96px] md:max-lg:text-[3.375rem] md:max-lg:leading-[3.1875rem] md:max-lg:tracking-[-1.08px] 2xl:text-[6.5rem] 2xl:leading-[6.1875rem] 2xl:tracking-[-2.08px]" data-cid="n30" data-component="heading">
            CRAFTING CINEMATIC
            <br className="inline" data-cid="n31" />
            <span className="inline text-primary [text-shadow:var(--clr-9)_0px_0px_50px]" data-cid="n32">
              REALITIES
            </span>
          </h1>
          {" "}
          <p className="w-full max-w-162.5 border-l-[3px] border-solid border-l-primary block mb-10 pl-5 text-color-014 text-[1.1875rem] leading-[2.0625rem] max-lg:leading-[1.6875rem] max-lg:[font-size:inherit]" data-cid="n33">
            Get to know the creative minds and technological powerhouse behind Focus VFX Studio.
          </p>
          {" "}
        </div>
        {" "}
        <div className="w-[55.5px] h-[4.6875rem] flex absolute bottom-10 left-16 z-5 min-w-0 flex-col items-center gap-3 text-color-005 [font-family:Outfit,_sans-serif] text-[0.625rem] font-bold leading-[0.8125rem] tracking-[2.6px]" data-cid="n34">
          <span className="block" data-cid="n35">
            SCROLL
          </span>
          {" "}
          <div className="w-px h-12.5 block opacity-[0.951498] [animation-name:scrollPulse] [animation-duration:2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite]" style={{ backgroundImage: "linear-gradient(var(--color-005), var(--clr-4))" }} data-cid="n36" />
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-32 bg-background max-lg:py-16" data-cid="n37">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n38">
          <div className="grid items-center gap-20 grid-cols-[619.625px_516.375px] max-lg:gap-10 max-lg:grid-cols-1" data-cid="n39">
            <div className="block" data-cid="n40">
              <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n41">
                OUR STORY
              </span>
              {" "}
              <h2 className="block mb-6 [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[-0.8px] uppercase" data-cid="n42" data-component="heading">
                WHO WE ARE
              </h2>
              {" "}
              <p className="block mb-6 text-color-001 text-[1.0625rem] leading-[1.875rem]" data-cid="n43">
                {" Founded by a collective of visual visionaries and technological innovators, Focus VFX Studio has grown to become a leading post-production house delivering top-tier CGI, compositing, and visual effects solutions. "}
              </p>
              {" "}
              <p className="block mb-6 text-color-001 text-[1.0625rem] leading-[1.875rem]" data-cid="n44">
                {" Based in Chennai, India, we service national and international filmmakers, OTT platforms, global advertising agencies, and enterprise clients. Our goal is simple: to transform abstract imaginations into stunning photorealistic realities that engage audiences. "}
              </p>
              {" "}
              <div className="flex mt-10 items-center gap-4" data-cid="n45">
                <img className="w-[4.6875rem] h-12.5 block max-w-full overflow-clip" data-cid="n46" data-component="image" alt="TPN Certified Studio" src="/assets/cloned/images/b6106541035f.png" />
                {" "}
                <div className="block" data-cid="n47">
                  <span className="block [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[1.44px] whitespace-nowrap" data-cid="n48">
                    TPN GLOBAL CERTIFIED
                  </span>
                  {" "}
                  <span className="inline text-primary text-xs font-bold leading-[0.9375rem] tracking-[0.6px]" data-cid="n49">
                    SECURE FACILITY
                  </span>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="block" data-cid="n50">
              <div className="h-112.5 border border-solid border-color-003 block relative rounded-sm bg-cover [background-position:50%_50%] shadow-[var(--clr-15)_0px_20px_40px_0px] max-lg:h-75" style={{ backgroundImage: "url(\"/assets/cloned/images/comp.jpeg\")" }} data-cid="n51">
                <div className="h-full block absolute top-0 inset-x-0" style={{ backgroundImage: "radial-gradient(circle, var(--clr-27) 0%, var(--clr-4) 70%)" }} data-cid="n52" />
                {" "}
              </div>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="border-t border-solid border-t-border border-b border-b-border block relative py-32 bg-color-002 max-lg:py-16" data-cid="n53">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n54">
          <div className="grid gap-12 grid-cols-2 max-lg:grid-cols-1" data-cid="n55">
            <div className="border border-solid border-border block py-14 px-10 rounded-sm text-center bg-color-002" data-cid="n56">
              <div className="block mb-6 text-primary text-[2.5rem] leading-[3.0625rem] [text-shadow:var(--accent)_0px_0px_10px]" data-cid="n57">
                <i className="inline-block [font-family:'Font_Awesome_6_Free'] font-black leading-10 before:content-[''] before:text-primary before:text-[2.5rem] before:font-black before:leading-10 before:text-center" data-cid="n58" />
              </div>
              {" "}
              <h3 className="block mb-4 [font-family:Outfit,_sans-serif] text-2xl font-extrabold leading-7.5 tracking-[-0.48px] uppercase" data-cid="n59" data-component="heading">
                OUR VISION
              </h3>
              {" "}
              <p className="block text-color-001 text-[0.9375rem] leading-[1.625rem]" data-cid="n60">
                To be globally recognized as a premier benchmark for visual effects storytelling, redefining cinema boundaries through the constant integration of emerging tech and art.
              </p>
              {" "}
            </div>
            {" "}
            <div className="border border-solid border-border block py-14 px-10 rounded-sm text-center bg-color-002" data-cid="n61">
              <div className="block mb-6 text-primary text-[2.5rem] leading-[3.0625rem] [text-shadow:var(--accent)_0px_0px_10px]" data-cid="n62">
                <i className="inline-block [font-family:'Font_Awesome_6_Free'] font-black leading-10 before:content-[''] before:text-primary before:text-[2.5rem] before:font-black before:leading-10 before:text-center" data-cid="n63" />
              </div>
              {" "}
              <h3 className="block mb-4 [font-family:Outfit,_sans-serif] text-2xl font-extrabold leading-7.5 tracking-[-0.48px] uppercase" data-cid="n64" data-component="heading">
                OUR MISSION
              </h3>
              {" "}
              <p className="block text-color-001 text-[0.9375rem] leading-[1.625rem]" data-cid="n65">
                To deliver seamless, high-fidelity visual assets by fostering an ecosystem of creative freedom, equipping our artists with elite pipelines, and maintaining ironclad delivery compliance.
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="border-t border-solid border-t-border border-b border-b-border block relative py-32 bg-color-002 max-lg:py-16" data-cid="n66" id="services">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n67">
          <div className="block relative mb-16 text-center max-lg:mb-10" data-cid="n68">
            <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n69">
              WHAT WE EXCEL AT
            </span>
            {" "}
            <h2 className="inline-block relative [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[2px] uppercase max-md:text-[1.625rem] max-md:leading-[2.0625rem] max-md:tracking-[1.28px] md:max-lg:text-[1.8125rem] md:max-lg:leading-9 md:max-lg:tracking-[1.44px] after:content-[''] after:block after:absolute after:top-[3.5625rem] after:right-[97.1px] after:-bottom-2.5 after:left-[9.8125rem] after:w-15 after:h-[0.1875rem] after:bg-primary after:shadow-[var(--primary)_0px_0px_10px_0px] after:transform-[matrix(1,0,0,1,-30,0)] after:origin-[0px_1.5px] max-md:after:top-10 max-md:after:right-[40.5px] max-md:after:left-[100.5px] md:max-lg:after:top-[2.6875rem] md:max-lg:after:right-[53.1px] md:max-lg:after:left-[113.1px]" data-cid="n70" data-component="heading">
              OUR SERVICES
            </h2>
            {" "}
          </div>
          {" "}
          <div className="grid gap-6 grid-cols-3 max-lg:gap-5 max-lg:grid-cols-1" data-cid="n71">
            {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} cids={FeatureCard_cids[i]} styles={FeatureCard_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <div className="block" data-cid="n127" id="footer-placeholder">
        <footer className="border-t border-solid border-t-border block relative z-10 pt-20 pb-8 bg-background" data-cid="n128" id="site-footer">
          <div className="block max-w-320 px-8 max-lg:max-w-full 2xl:mx-80" data-cid="n129">
            <div className="grid mb-16 gap-12 grid-cols-[357.328px_178.672px_214.391px_321.609px] max-lg:gap-10 max-lg:text-center max-lg:grid-cols-1" data-cid="n130">
              <div className="flex flex-col max-lg:items-center" data-cid="n131">
                <a className="h-26 block cursor-pointer" data-cid="n132" data-component="link" href="/">
                  {" "}
                  <img className="w-46.5 h-20 block max-w-full mb-6 overflow-clip [filter:drop-shadow(var(--clr-0)_0px_0px_5px)]" data-cid="n133" data-component="image" alt="Focus VFX Studio" src="/assets/cloned/images/f068e3c48022.png" />
                  {" "}
                </a>
                {" "}
                <p className="block mb-6 text-color-001 text-sm leading-[1.4375rem]" data-cid="n134">
                  {" Delivering premium Hollywood-grade Visual Effects, CGI, Motion Graphics, and Post Production solutions for films, advertising agencies, and corporate clients globally. "}
                </p>
                {" "}
                <div className="block mb-6" data-cid="n135">
                  <img className="w-45 h-30 block max-w-full overflow-clip max-md:w-[5.1875rem] max-md:h-[3.4375rem] md:max-lg:w-[6.5625rem] md:max-lg:h-17.5" data-cid="n136" data-component="image" alt="TPN Certified" src="/assets/cloned/images/b6106541035f.png" title="TPN Global Certified" />
                  {" "}
                </div>
                {" "}
                <div className="flex gap-[0.8rem] max-lg:justify-center" data-cid="n137">
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n138" data-component="link" aria-label="Instagram" href="https://www.instagram.com/focusvfx.official?igsh=b2xrNXBrMWU4emc5" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n139" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n140" data-component="link" aria-label="Facebook" href="https://www.facebook.com/share/1DC53weRmh/?mibextid=wwXIfr" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n141" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n142" data-component="link" aria-label="LinkedIn" href="https://www.linkedin.com/company/focus-vfx-pvt-ltd/" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n143" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n144" data-component="link" aria-label="X (Twitter)" href={"https://x.com/focus_vfx?s=21&t=uCjnNgro9kkL-sZe8yA5Bw"} target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n145" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n146" data-component="link" aria-label="Vimeo" href={"https://vimeo.com/user193282489?fl=pp&fe=sh"} target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n147" />
                  </a>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n148">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[148.7px] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n149" data-component="heading">
                  Quick Links
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n150">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n161">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[11.525rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n162" data-component="heading">
                  VFX Services
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n163">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col max-lg:items-center" data-cid="n186">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[18.225rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-lg:after:right-[5.825rem]" data-cid="n187" data-component="heading">
                  Studio Info
                </h4>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n188">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n189" />
                  {" "}
                  <span className="block" data-cid="n190">
                    No.33, Balammal Building,
                    <br className="inline" data-cid="n191" />
                    Burkit Road, T. Nagar,
                    <br className="inline" data-cid="n192" />
                    Chennai - 600017
                  </span>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n193">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n194" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n195" data-component="link" href="tel:+918925902036">
                    +91 8925902036
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n196">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n197" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n198" data-component="link" href="mailto:info@focusvfx.in">
                    info@focusvfx.in
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n199">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n200" />
                  {" "}
                  <span className="block" data-cid="n201">
                    Mon - Sat: 09:00 AM - 06:00 PM
                  </span>
                  {" "}
                </p>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="border-t border-solid border-t-border flex pt-8 flex-wrap justify-between items-center gap-4" data-cid="n202">
              <p className="block text-color-001 text-sm leading-4" data-cid="n203">
                {"© "}
                <span className="inline" data-cid="n204" id="copyright-year">
                  2026
                </span>
                {" Focus VFX Studio. All Rights Reserved."}
              </p>
              {" "}
              <p className="block text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[1.36px] uppercase" data-cid="n205">
                Crafting Visual Wonders Beyond Imagination
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      <div className="w-2 h-2 block fixed top-[246.7875rem] left-0 z-10000 rounded-[50%] bg-primary transform-[matrix(1,0,0,1,-4,-4)] pointer-events-none max-lg:hidden 2xl:top-px 2xl:left-px" data-cid="n206" />
      <div className="w-8 h-8 border border-solid border-color-004 block fixed top-0 left-0 z-10000 rounded-[50%] transform-[matrix(1,0,0,1,-16,-16)] pointer-events-none max-lg:hidden 2xl:top-px 2xl:left-px" data-cid="n207" />
    </>
  );
}
