import "./ditto.css";
import FeatureCard from "./components/feature-card";
import FeatureCard2 from "./components/feature-card2";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const FeatureCard_data = [
  { title: "Creative Freedom", description: "We encourage artistic exploration, visual brainstorming, and out-of-the-box solving of design challenges." },
  { title: "Global Projects", description: "Our portfolio includes projects from national feature films to major international streaming platforms." },
  { title: "Career Growth", description: "Access to structured feedback loops, technical training, and clear pathways to lead and supervisor positions." },
  { title: "Latest Tools", description: "Work with elite VFX setups and high-performance dedicated rendering pipelines." },
  { title: "Friendly Environment", description: "A highly collaborative, welcoming studio culture that values work-life balance and artist health." }
];
const FeatureCard2_data = [
  { id: "job-motion-designer", title: "Motion Graphics Designer", text: " Design Department", text2: " Full-Time / Hybrid", text3: " 2 - 4 Years", text4: " Chennai", description: "We want a Motion Graphics Designer to build sleek title animations, premium promotional assets, social media videos, and futuristic UI designs for movies and commercial ads.", text5: "Design and animate title cards, lower thirds, UI mockups, and corporate videos.", text6: "Create high-end motion graphics assets for client presentations and reels.", text7: "Participate in brainstorming sessions and style frame development.", text8: "Stay updated on modern design aesthetics, kinetics, and typographic animations.", text9: "Advanced knowledge of industry-standard motion graphics and design.", text10: "Experience with 3D design is a massive plus.", text11: "Strong sense of timing, typography, design, and layout.", text12: "Ability to handle multiple design tasks and adapt to changing creative briefs." },
  { id: "job-three-d-artist", title: "3D Artist", text: " 3D Asset Department", text2: " Full-Time", text3: " 3+ Years", text4: " Chennai (On-site)", description: "We need a 3D Artist specializing in photorealistic modeling, texturing, and shading. You will build sets, props, vehicles, and creatures that form the foundation of our CGI pipeline.", text5: "Create high-poly and low-poly 3D models of characters, environments, and props.", text6: "Unwrap UVs and create detailed textures (PBR materials).", text7: "Develop shaders and lighting setups for realistic rendering.", text8: "Collaborate with animators and riggers to ensure model readiness.", text9: "Expertise in industry-standard 3D modeling and texturing.", text10: "Understanding of modern rendering engines.", text11: "Familiarity with anatomy, proportions, topology, and surface qualities.", text12: "Strong visual reference matching capabilities." },
  { id: "job-video-editor", title: "Video Editor", text: " Post-Production", text2: " Full-Time", text3: " 2 - 4 Years", text4: " Chennai (On-site)", description: "We are seeking a Video Editor to shape showreels, teasers, and promotional materials. You will cut footage, synchronize sound, and coordinate with colorists and sound designers.", text5: "Edit high-pace showreels, cinematic trailers, and behind-the-scenes content.", text6: "Organize post-production assets and manage edit timelines.", text7: "Collaborate with the sound department to select music and sound effects.", text8: "Integrate motion graphics and basic color grades into final drafts.", text9: "Proficiency in industry-standard video editing and color grading.", text10: "Strong narrative sense, rhythm, and pacing.", text11: "Basic understanding of VFX pipelines and post-production workflows.", text12: "Excellent organization and attention to detail." },
  { id: "job-roto-artist", title: "Roto Artist", text: " Compositing Support", text2: " Full-Time / Contract", text3: " 1 - 3 Years", text4: " Chennai (On-site)", description: "Seeking Junior to Mid-level Roto Artists to support our high-end compositing team. You will create pixel-perfect matte outlines for characters, actors, and objects in motion.", text5: "Generate detailed and consistent rotoscope mattes.", text6: "Execute plate cleanups, wire/rig removals, and plate reconstructions.", text7: "Interact with lead compositors to match visual requirements.", text8: "Maintain clean project nodes and folder hierarchy.", text9: "Solid knowledge of industry-standard ROTO and compositing.", text10: "Understanding of motion blur, tracking, and edge feathering.", text11: "Extremely patient, detail-oriented, and focused.", text12: "Ability to handle high-turnaround assignments under tight deadlines." }
];
const Tile_data = [
  { text: " Designing" },
  { text: " Full Time" },
  { text: " 2-4" },
  { text: " Chennai" }
];
const Tile_data2 = [
  { text: " FX Department" },
  { text: " Full-Time" },
  { text: " 3 - 5 Years" },
  { text: " Chennai (On-site)" }
];
const Tile2_data = [
  { disabled: true, selected: true, value: "", text: "Select a position" },
  { value: "Compositor", text: "Compositor" },
  { value: "Motion Graphics Designer", text: "Motion Graphics Designer" },
  { value: "3D Artist", text: "3D Artist" },
  { value: "Video Editor", text: "Video Editor" },
  { value: "Roto Artist", text: "Roto Artist" },
  { value: "Paint & Prez Artist", text: "Paint & Prez Artist" },
  { value: "FX Artist", text: "FX Artist" }
];
const ListRow_data = [
  { href: "/index.html", label: "Home" },
  { href: "/about.html", label: "About Us" },
  { href: "/works.html", label: "Our Works" },
  { href: "/career.html", label: "Careers" },
  { href: "/contact.html", label: "Contact Us" }
];
const ListRow2_data = [
  { label: "PREP" },
  { label: "Story Board" },
  { label: "Story Telling" },
  { label: "CGI Production" },
  { label: "Motion Graphics" },
  { label: "3D Animation" },
  { label: "Compositing" },
  { label: "ROTO" },
  { label: "Matchmovie" },
  { label: "Colour Grading" },
  { label: "Digital Cleanup" }
];
const FeatureCard_cids: string[][] = [
  ["n47", "n48", "n49", "n50", "n51"],
  ["n52", "n53", "n54", "n55", "n56"],
  ["n57", "n58", "n59", "n60", "n61"],
  ["n62", "n63", "n64", "n65", "n66"],
  ["n67", "n68", "n69", "n70", "n71"]
];
const FeatureCard2_cids: string[][] = [
  ["n104", "n105", "n106", "n107", "n108", "n109", "n110", "n111", "n112", "n113", "n114", "n115", "n116", "n117", "n118", "n119", "n120", "n121", "n122", "n123", "n124", "n125", "n126", "n127", "n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135"],
  ["n136", "n137", "n138", "n139", "n140", "n141", "n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149", "n150", "n151", "n152", "n153", "n154", "n155", "n156", "n157", "n158", "n159", "n160", "n161", "n162", "n163", "n164", "n165", "n166", "n167"],
  ["n168", "n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181", "n182", "n183", "n184", "n185", "n186", "n187", "n188", "n189", "n190", "n191", "n192", "n193", "n194", "n195", "n196", "n197", "n198", "n199"],
  ["n200", "n201", "n202", "n203", "n204", "n205", "n206", "n207", "n208", "n209", "n210", "n211", "n212", "n213", "n214", "n215", "n216", "n217", "n218", "n219", "n220", "n221", "n222", "n223", "n224", "n225", "n226", "n227", "n228", "n229", "n230", "n231"]
];
const Tile_cids: string[][] = [
  ["n237", "n238"],
  ["n239", "n240"],
  ["n241", "n242"],
  ["n243", "n244"]
];
const Tile_cids2: string[][] = [
  ["n261", "n262"],
  ["n263", "n264"],
  ["n265", "n266"],
  ["n267", "n268"]
];
const Tile2_cids: string[][] = [
  ["n304"],
  ["n305"],
  ["n306"],
  ["n307"],
  ["n308"],
  ["n309"],
  ["n310"],
  ["n311"]
];
const ListRow_cids: string[][] = [
  ["n352", "n353"],
  ["n354", "n355"],
  ["n356", "n357"],
  ["n358", "n359"],
  ["n360", "n361"]
];
const ListRow2_cids: string[][] = [
  ["n365", "n366"],
  ["n367", "n368"],
  ["n369", "n370"],
  ["n371", "n372"],
  ["n373", "n374"],
  ["n375", "n376"],
  ["n377", "n378"],
  ["n379", "n380"],
  ["n381", "n382"],
  ["n383", "n384"],
  ["n385", "n386"]
];
const FeatureCard_styles = [
  { className: "before:bottom-[18.95rem]", className2: "before:content-['']" },
  { className: "before:bottom-[18.95rem]", className2: "before:content-['']" },
  { className: "before:bottom-[18.95rem]", className2: "before:content-['']" },
  { className: "before:bottom-[18.95rem]", className2: "before:content-['']" },
  { className: "before:bottom-[19.075rem]", className2: "before:content-['']" }
];
const FeatureCard2_styles = [
  { className: "max-md:before:bottom-[2.875rem]", className2: "max-md:before:bottom-[2.875rem]", className3: "max-md:before:bottom-[2.875rem]", className4: "max-md:before:bottom-[2.875rem]", className5: "max-md:before:bottom-[2.875rem]", className6: "max-md:before:bottom-[1.4375rem]", className7: "max-md:before:bottom-[2.875rem]" },
  { className: "max-md:before:bottom-[2.875rem]", className2: "max-md:before:bottom-[1.4375rem]", className3: "max-md:before:bottom-[1.4375rem]", className4: "max-md:before:bottom-[2.875rem]", className5: "max-md:before:bottom-[1.4375rem]", className6: "max-md:before:bottom-[2.875rem]", className7: "max-md:before:bottom-[1.4375rem]" },
  { className: "max-md:before:bottom-[2.875rem]", className2: "max-md:before:bottom-[1.4375rem]", className3: "max-md:before:bottom-[2.875rem]", className4: "max-md:before:bottom-[2.875rem]", className5: "max-md:before:bottom-[1.4375rem]", className6: "max-md:before:bottom-[2.875rem]", className7: "max-md:before:bottom-[1.4375rem]" },
  { className: "max-md:before:bottom-[1.4375rem]", className2: "max-md:before:bottom-[2.875rem]", className3: "max-md:before:bottom-[1.4375rem]", className4: "max-md:before:bottom-[1.4375rem]", className5: "max-md:before:bottom-[2.875rem]", className6: "max-md:before:bottom-[1.4375rem]", className7: "max-md:before:bottom-[2.875rem]" }
];
const Tile_styles = [
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" }
];
const Tile_styles2 = [
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" }
];

export default function Page() {
  return (
    <>
      <section className="h-170 min-h-170 flex relative pt-20 items-center overflow-hidden bg-background max-md:h-[45.625rem] max-md:min-h-[43.1375rem] md:max-lg:h-[54.4rem] md:max-lg:min-h-[54.4rem] 2xl:h-229.5 2xl:min-h-229.5" data-cid="n22">
        <div className="h-full block absolute top-0 inset-x-0 z-0 min-w-0" data-cid="n23">
          <div className="w-320 h-170 block absolute top-0 left-0 bg-cover [background-position:50%_0%] [filter:grayscale(0.8)_brightness(0.3)_contrast(1.2)] [animation-name:bgSlowZoom] [animation-duration:12s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] [animation-direction:alternate] max-md:w-[23.4375rem] max-md:h-[45.625rem] md:max-lg:w-192 md:max-lg:h-[54.4rem] 2xl:w-480 2xl:h-229.5" style={{ backgroundImage: "url(\"/assets/cloned/images/5ba565cae533.png\")" }} data-cid="n24" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 z-1" style={{ backgroundImage: "linear-gradient(135deg, var(--clr-6) 0%, var(--clr-12) 60%, var(--clr-2) 100%)" }} data-cid="n25" />
          {" "}
          <div className="w-125 h-125 block absolute -top-17 -left-32 z-2 opacity-[0.545814] [mix-blend-mode:screen] [filter:blur(60px)] [animation-name:volumetricPulse] [animation-duration:6s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] pointer-events-none max-md:-top-[4.5625rem] max-md:left-[-37.5px] md:max-lg:-top-[5.4375rem] md:max-lg:-left-[4.8rem] 2xl:-top-[5.7375rem] 2xl:-left-48" style={{ backgroundImage: "radial-gradient(at 70% 40%, var(--clr-26) 0%, var(--clr-4) 55%)" }} data-cid="n26" />
          {" "}
          <img className="w-320 h-170 block absolute z-3 overflow-clip aspect-[auto_1280/680] pointer-events-none max-md:w-[23.4375rem] max-md:h-182.5 max-md:aspect-[auto_375/730] md:max-lg:w-192 md:max-lg:h-217.5 md:max-lg:aspect-[auto_768/870] 2xl:w-480 2xl:h-229.5 2xl:aspect-[auto_1920/918]" data-cid="n27" height="680" id="hero-particles" src="/assets/cloned/images/56ea4cef4caa.png" width="1280" alt="" />
          {" "}
        </div>
        {" "}
        <div className="block relative z-10 max-w-320 mx-[2.3875rem] py-16 px-8 text-left max-lg:max-w-full max-md:mx-0 md:max-lg:mx-2.5 2xl:mx-80" data-cid="n28">
          <span className="border border-solid border-color-006 inline-block mb-6 py-[0.4rem] px-4 rounded-[50px] text-primary [font-family:Outfit,_sans-serif] text-xs font-bold leading-[0.9375rem] tracking-[3.46px] uppercase" data-cid="n29">
            JOIN OUR TEAM — FOCUS VFX STUDIO
          </span>
          {" "}
          <h1 className="block mb-6 text-[5.625rem] font-black leading-[5.3125rem] tracking-[-1.79px] uppercase max-md:text-5xl max-md:leading-[2.875rem] max-md:tracking-[-0.96px] md:max-lg:text-[3.375rem] md:max-lg:leading-[3.1875rem] md:max-lg:tracking-[-1.08px] 2xl:text-[6.5rem] 2xl:leading-[6.1875rem] 2xl:tracking-[-2.08px]" data-cid="n30" data-component="heading">
            BUILD THE FUTURE
            <br className="inline" data-cid="n31" />
            {"OF "}
            <span className="inline text-primary [text-shadow:var(--clr-9)_0px_0px_50px]" data-cid="n32">
              VISUAL STORYTELLING
            </span>
          </h1>
          {" "}
          <p className="w-full max-w-162.5 border-l-[3px] border-solid border-l-primary block mb-10 pl-5 text-color-014 text-[1.1875rem] leading-[2.0625rem] max-lg:leading-[1.6875rem] max-lg:[font-size:inherit]" data-cid="n33">
            Work alongside top-tier directors, state-of-the-art pipelines, and push your artistic limits on world-class productions.
          </p>
          {" "}
          <div className="flex flex-wrap gap-4" data-cid="n34">
            <a className="w-[221.7px] h-[2.5625rem] border border-solid border-clr-4 flex relative z-1 opacity-0 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] transform-[matrix(0.95,0,0,0.95,0,20)] origin-[110.859px_20.5px] cursor-pointer" data-cid="n35" href="#openings">
              {"VIEW OPEN ROLES "}
              <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-background before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px] before:text-left" data-cid="n36" />
            </a>
            {" "}
            <a className="w-[154.5px] h-[2.5625rem] border border-solid border-surface-4 flex relative z-1 opacity-0 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-[0.8125rem] font-semibold leading-[0.9375rem] tracking-[1.28px] uppercase transform-[matrix(0.95,0,0,0.95,0,20)] origin-[77.2344px_20.5px] cursor-pointer" data-cid="n37" href="#apply-form-section">
              APPLY NOW
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
        <div className="w-[55.5px] h-[4.6875rem] flex absolute bottom-10 left-16 z-5 min-w-0 flex-col items-center gap-3 text-color-005 [font-family:Outfit,_sans-serif] text-[0.625rem] font-bold leading-[0.8125rem] tracking-[2.6px]" data-cid="n38">
          <span className="block" data-cid="n39">
            SCROLL
          </span>
          {" "}
          <div className="w-px h-12.5 block opacity-[0.91238] [animation-name:scrollPulse] [animation-duration:2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite]" style={{ backgroundImage: "linear-gradient(var(--color-005), var(--clr-4))" }} data-cid="n40" />
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-32 bg-background max-lg:py-16" data-cid="n41" id="benefits">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n42">
          <div className="block relative mb-16 text-center max-lg:mb-10" data-cid="n43">
            <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n44">
              STUDIO CULTURE
            </span>
            {" "}
            <h2 className="inline-block relative [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[2px] uppercase max-md:text-[1.625rem] max-md:leading-[2.0625rem] max-md:tracking-[1.28px] md:max-lg:text-[1.8125rem] md:max-lg:leading-9 md:max-lg:tracking-[1.44px] after:content-[''] after:block after:absolute after:top-[3.5625rem] after:right-[5.125rem] after:-bottom-2.5 after:left-[8.875rem] after:w-15 after:h-[0.1875rem] after:bg-primary after:shadow-[var(--primary)_0px_0px_10px_0px] after:transform-[matrix(1,0,0,1,-30,0)] after:origin-[0px_1.5px] max-md:after:top-10 max-md:after:right-[1.9375rem] max-md:after:left-[5.6875rem] md:max-lg:after:top-[2.6875rem] md:max-lg:after:right-[42.3px] md:max-lg:after:left-[102.3px]" data-cid="n45" data-component="heading">
              WHY JOIN US
            </h2>
            {" "}
          </div>
          {" "}
          <div className="grid mt-12 gap-8 grid-cols-[repeat(auto-fit,_minmax(279px,_1fr))] grid-rows-2 max-md:grid-rows-5 md:max-lg:grid-rows-3" data-cid="n46">
            {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} cids={FeatureCard_cids[i]} styles={FeatureCard_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="border-t border-solid border-t-border border-b border-b-border block relative py-32 bg-color-002 max-lg:py-16" data-cid="n72" id="openings">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n73">
          <div className="block relative mb-16 text-center max-lg:mb-10" data-cid="n74">
            <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n75">
              CAREER OPPORTUNITIES
            </span>
            {" "}
            <h2 className="inline-block relative [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[2px] uppercase max-md:text-[1.625rem] max-md:leading-[2.0625rem] max-md:tracking-[1.28px] md:max-lg:text-[1.8125rem] md:max-lg:leading-9 md:max-lg:tracking-[1.44px] after:content-[''] after:block after:absolute after:top-[3.5625rem] after:right-[125.5px] after:-bottom-2.5 after:left-[11.5875rem] after:w-15 after:h-[0.1875rem] after:bg-primary after:shadow-[var(--primary)_0px_0px_10px_0px] after:transform-[matrix(1,0,0,1,-30,0)] after:origin-[0px_1.5px] max-md:after:top-10 max-md:after:right-[58.7px] max-md:after:left-[118.7px] md:max-lg:after:top-[2.6875rem] md:max-lg:after:right-[73.5px] md:max-lg:after:left-[133.5px]" data-cid="n76" data-component="heading">
              OPEN POSITIONS
            </h2>
            {" "}
          </div>
          {" "}
          <div className="flex mt-12 flex-col gap-6" data-cid="n77" id="careers-positions-container">
            <div className="border border-solid border-border block rounded-sm overflow-hidden bg-color-002" data-cid="n78" id="job-compositor">
              <div className="flex p-8 justify-between items-center cursor-pointer" data-cid="n79">
                <div className="block" data-cid="n80">
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-2xl font-extrabold leading-7.5 tracking-[-0.48px] uppercase" data-cid="n81" data-component="heading">
                    Compositor
                  </h3>
                  {" "}
                  <div className="flex gap-6 text-color-001 text-sm leading-4" data-cid="n82">
                    <span className="flex items-center gap-[0.4rem]" data-cid="n83">
                      <i className="block text-primary [font-family:'Font_Awesome_6_Free'] font-black leading-[0.875rem] before:content-[''] before:text-primary before:text-sm before:font-black before:leading-[0.875rem]" data-cid="n84" />
                      {" Compositing"}
                    </span>
                    {" "}
                    <span className="flex items-center gap-[0.4rem]" data-cid="n85">
                      <i className="block text-primary [font-family:'Font_Awesome_6_Free'] font-black leading-[0.875rem] before:content-[''] before:text-primary before:text-sm before:font-black before:leading-[0.875rem]" data-cid="n86" />
                      {" Full-Time"}
                    </span>
                    {" "}
                    <span className="flex items-center gap-[0.4rem]" data-cid="n87">
                      <i className="block text-primary [font-family:'Font_Awesome_6_Free'] font-black leading-[0.875rem] before:content-[''] before:text-primary before:text-sm before:font-black before:leading-[0.875rem]" data-cid="n88" />
                      {" "}
                    </span>
                    {" "}
                    <span className="flex items-center gap-[0.4rem]" data-cid="n89">
                      <i className="block text-primary [font-family:'Font_Awesome_6_Free'] font-black leading-[0.875rem] before:content-[''] before:text-primary before:text-sm before:font-black before:leading-[0.875rem]" data-cid="n90" />
                      {" Chennai (On-site)"}
                    </span>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <button className="w-10 h-10 border border-solid border-surface-2 flex rounded-[50%] justify-center items-center [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center cursor-default max-md:w-[15.3px]" data-cid="n91" data-component="button" aria-label="Toggle Details">
                  <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-foreground before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:text-center" data-cid="n92" />
                  {" "}
                </button>
                {" "}
              </div>
              {" "}
              <div className="border-t border-solid border-t-clr-4 block max-h-0 overflow-hidden" data-cid="n93">
                <div className="block p-8" data-cid="n94">
                  <p className="block mb-6 text-color-001 text-[0.9375rem] leading-[1.625rem]" data-cid="n95">
                    Looking for a Compositor with an eye for detail, color, and realism. You will be responsible for bringing together all CGI and live-action assets to form the final visual frames of our cinematic works.
                  </p>
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n96" data-component="heading">
                    Key Responsibilities
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n97">
                    <li className="list-item relative mb-2 pl-6 text-color-001 text-sm leading-[1.4375rem] before:content-['→'] before:block before:absolute before:top-0 before:right-[70.475rem] before:bottom-[2.875rem] before:left-0 before:w-[0.9rem] before:h-[1.4375rem] before:text-primary before:text-sm before:leading-[1.4375rem] max-md:before:right-[14.9125rem] max-md:before:bottom-[230.5px] md:max-lg:before:right-[39.475rem] md:max-lg:before:bottom-[69.1px]" data-cid="n98">
                      Merge 2D, 3D, and live-action plates into a cohesive and photorealistic shot.\nExecute keying, tracking, matte extractions, digital cleanups, and color matching.\nPerform high-precision ROTO and paintwork validation when needed.\nAddress feedback from VFX supervisors and deliver shots within tight deadlines.
                    </li>
                  </ul>
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n99" data-component="heading">
                    {"Qualifications & Requirements"}
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n100">
                    <li className="list-item relative mb-2 pl-6 text-color-001 text-sm leading-[1.4375rem] before:content-['→'] before:block before:absolute before:top-0 before:right-[70.475rem] before:bottom-[1.4375rem] before:left-0 before:w-[0.9rem] before:h-[1.4375rem] before:text-primary before:text-sm before:leading-[1.4375rem] max-md:before:right-[14.9125rem] max-md:before:bottom-[12.9625rem] md:max-lg:before:right-[39.475rem] md:max-lg:before:bottom-[69.1px]" data-cid="n101">
                      Mastery of industry-standard compositing.\nExpert understanding of 3D space, color spaces (ACES, sRGB), and camera lenses.\nExcellent eye for lighting, shadows, atmospheric integration, and photorealism.\nProblem-solving mindset and solid pipeline hygiene.
                    </li>
                  </ul>
                  {" "}
                  <div className="block mt-8" data-cid="n102">
                    <button className="border border-solid border-clr-4 inline-flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] text-center uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n103" data-component="button">
                      {" Apply For This Position "}
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {FeatureCard2_data.map((d, i) => <FeatureCard2 key={i} d={d} cids={FeatureCard2_cids[i]} styles={FeatureCard2_styles[i]} />)}
            <div className="border border-solid border-border block rounded-sm overflow-hidden bg-color-002" data-cid="n232" id="job-designer">
              <div className="flex p-8 justify-between items-center cursor-pointer" data-cid="n233">
                <div className="block" data-cid="n234">
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-2xl font-extrabold leading-7.5 tracking-[-0.48px] uppercase" data-cid="n235" data-component="heading">
                    {"Paint & Prez Artist"}
                  </h3>
                  {" "}
                  <div className="flex gap-6 text-color-001 text-sm leading-4" data-cid="n236">
                    {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} styles={Tile_styles[i]} />)}
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <button className="w-10 h-10 border border-solid border-surface-2 flex rounded-[50%] justify-center items-center [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center cursor-default max-md:w-[15.3px]" data-cid="n245" data-component="button" aria-label="Toggle Details">
                  <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-foreground before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:text-center" data-cid="n246" />
                  {" "}
                </button>
                {" "}
              </div>
              {" "}
              <div className="border-t border-solid border-t-clr-4 block max-h-0 overflow-hidden" data-cid="n247">
                <div className="block p-8" data-cid="n248">
                  <p className="block mb-6 text-color-001 text-[0.9375rem] leading-[1.625rem]" data-cid="n249">
                    dwiewio cnwiojrowur ncwiriowu c wsjrwiourwuro
                  </p>
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n250" data-component="heading">
                    Key Responsibilities
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n251" />
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n252" data-component="heading">
                    {"Qualifications & Requirements"}
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n253" />
                  {" "}
                  <div className="block mt-8" data-cid="n254">
                    <button className="border border-solid border-clr-4 inline-flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] text-center uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n255" data-component="button">
                      {" Apply For This Position "}
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            <div className="border border-solid border-border block rounded-sm overflow-hidden bg-color-002" data-cid="n256" id="job-fx-artist">
              <div className="flex p-8 justify-between items-center cursor-pointer" data-cid="n257">
                <div className="block" data-cid="n258">
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-2xl font-extrabold leading-7.5 tracking-[-0.48px] uppercase" data-cid="n259" data-component="heading">
                    FX Artist
                  </h3>
                  {" "}
                  <div className="flex gap-6 text-color-001 text-sm leading-4" data-cid="n260">
                    {Tile_data2.map((d, i) => <Tile key={i} d={d} cids={Tile_cids2[i]} styles={Tile_styles2[i]} />)}
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <button className="w-10 h-10 border border-solid border-surface-2 flex rounded-[50%] justify-center items-center [font-family:Arial] text-[0.8125rem] leading-[0.9375rem] text-center cursor-default max-md:w-[15.3px]" data-cid="n269" data-component="button" aria-label="Toggle Details">
                  <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-foreground before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:text-center" data-cid="n270" />
                  {" "}
                </button>
                {" "}
              </div>
              {" "}
              <div className="border-t border-solid border-t-clr-4 block max-h-0 overflow-hidden" data-cid="n271">
                <div className="block p-8" data-cid="n272">
                  <p className="block mb-6 text-color-001 text-[0.9375rem] leading-[1.625rem]" data-cid="n273">
                    We are seeking a highly creative and skilled VFX Artist to design and implement complex visual effects for feature films and OTT series. You will collaborate with supervisors and directors to translate cinematic visions into reality.
                  </p>
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n274" data-component="heading">
                    Key Responsibilities
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n275">
                    <li className="list-item relative mb-2 pl-6 text-color-001 text-sm leading-[1.4375rem] before:content-['→'] before:block before:absolute before:top-0 before:right-[70.475rem] before:bottom-[1.4375rem] before:left-0 before:w-[0.9rem] before:h-[1.4375rem] before:text-primary before:text-sm before:leading-[1.4375rem] max-md:before:right-[14.9125rem] max-md:before:bottom-[12.9625rem] md:max-lg:before:right-[39.475rem] md:max-lg:before:bottom-[69.1px]" data-cid="n276">
                      Create high-quality particle, fluid, dynamic, and physics simulations (smoke, fire, dust, debris, water).\nIntegrate CGI elements seamlessly with live-action plates.\nWork closely with VFX Supervisors to ensure visual styles match the creative brief.\nMaintain optimization and production-ready render setups.
                    </li>
                  </ul>
                  {" "}
                  <h4 className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[2.04px] uppercase" data-cid="n277" data-component="heading">
                    {"Qualifications & Requirements"}
                  </h4>
                  {" "}
                  <ul className="block mb-6 pl-2 [list-style-type:none] list-outside" data-cid="n278">
                    <li className="list-item relative mb-2 pl-6 text-color-001 text-sm leading-[1.4375rem] before:content-['→'] before:block before:absolute before:top-0 before:right-[70.475rem] before:bottom-[1.4375rem] before:left-0 before:w-[0.9rem] before:h-[1.4375rem] before:text-primary before:text-sm before:leading-[1.4375rem] max-md:before:right-[14.9125rem] max-md:before:bottom-[12.9625rem] md:max-lg:before:right-[39.475rem] md:max-lg:before:bottom-[2.875rem]" data-cid="n279">
                      Strong proficiency in industry-standard VFX and 3D animation.\nDeep understanding of physical dynamics, composition, color, and lighting.\nProven track record with a high-end portfolio or showreel.\nExperience working in a collaborative VFX studio pipeline.
                    </li>
                  </ul>
                  {" "}
                  <div className="block mt-8" data-cid="n280">
                    <button className="border border-solid border-clr-4 inline-flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] text-center uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n281" data-component="button">
                      {" Apply For This Position "}
                    </button>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-32 bg-background max-lg:py-16" data-cid="n282" id="apply-form-section">
        <div className="block max-w-200 mx-auto px-8 max-lg:px-6" data-cid="n283">
          <div className="block relative mb-16 text-center max-lg:mb-10" data-cid="n284">
            <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n285">
              JOIN THE COHORT
            </span>
            {" "}
            <h2 className="inline-block relative [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[2px] uppercase max-md:text-[1.625rem] max-md:leading-[2.0625rem] max-md:tracking-[1.28px] md:max-lg:text-[1.8125rem] md:max-lg:leading-9 md:max-lg:tracking-[1.44px] after:content-[''] after:block after:absolute after:top-[3.5625rem] after:right-[4.2625rem] after:-bottom-2.5 after:left-32 after:w-15 after:h-[0.1875rem] after:bg-primary after:shadow-[var(--primary)_0px_0px_10px_0px] after:transform-[matrix(1,0,0,1,-30,0)] after:origin-[0px_1.5px] max-md:after:top-10 max-md:after:right-[1.375rem] max-md:after:left-[5.125rem] md:max-lg:after:top-[2.6875rem] md:max-lg:after:right-[32.3px] md:max-lg:after:left-[92.3px]" data-cid="n286" data-component="heading">
              APPLY NOW
            </h2>
            {" "}
          </div>
          {" "}
          <div className="border border-solid border-border block p-12 rounded-sm bg-color-002 shadow-[var(--clr-13)_0px_20px_40px_0px] max-lg:py-8 max-lg:px-6" data-cid="n287">
            <form className="block" data-cid="n288" id="careers-apply-form">
              <div className="block" data-cid="n289" id="dynamic-form-container">
                <div className="grid gap-8 grid-cols-2 max-lg:grid-cols-1 max-lg:gap-[initial]" data-cid="n290">
                  <div className="block relative mb-8" data-cid="n291">
                    <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n292" htmlFor="apply-name">
                      Full Name *
                    </label>
                    {" "}
                    <input className="w-full h-12.5 border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] overflow-clip text-[0.9375rem] leading-[1.1875rem] bg-color-010 cursor-text" data-cid="n293" data-component="input" id="apply-name" name="name" placeholder="e.g. John Doe" type="text" />
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative mb-8" data-cid="n294">
                    <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n295" htmlFor="apply-email">
                      Email Address *
                    </label>
                    {" "}
                    <input className="w-full h-12.5 border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] overflow-clip text-[0.9375rem] leading-[1.1875rem] bg-color-010 cursor-text" data-cid="n296" data-component="input" id="apply-email" name="email" placeholder="e.g. john@example.com" type="email" />
                    {" "}
                  </div>
                  {" "}
                </div>
                <div className="grid gap-8 grid-cols-2 max-lg:grid-cols-1 max-lg:gap-[initial]" data-cid="n297">
                  <div className="block relative mb-8" data-cid="n298">
                    <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n299" htmlFor="apply-phone">
                      Mobile Number *
                    </label>
                    {" "}
                    <input className="w-full h-12.5 border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] overflow-clip text-[0.9375rem] leading-[1.1875rem] bg-color-010 cursor-text" data-cid="n300" data-component="input" id="apply-phone" name="phone" placeholder="e.g. 9876543210" type="tel" />
                    {" "}
                  </div>
                  {" "}
                  <div className="block relative mb-8" data-cid="n301">
                    <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n302" htmlFor="apply-position">
                      Position Applying For *
                    </label>
                    {" "}
                    <select className="w-full h-13 border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] items-center text-[0.9375rem] leading-[1.1875rem] whitespace-pre text-nowrap bg-color-010 cursor-default" data-cid="n303" data-component="select" id="apply-position" name="position">
                      {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} />)}
                    </select>
                    {" "}
                  </div>
                  {" "}
                </div>
                <div className="grid gap-8 grid-cols-2 max-lg:grid-cols-1 max-lg:gap-[initial]" data-cid="n312">
                  <div className="block relative mb-8" data-cid="n313">
                    <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n314" htmlFor="apply-portfolio">
                      Portfolio URL
                    </label>
                    {" "}
                    <input className="w-full h-12.5 border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] overflow-clip text-[0.9375rem] leading-[1.1875rem] bg-color-010 cursor-text" data-cid="n315" data-component="input" id="apply-portfolio" name="portfolio" placeholder="e.g. https://behance.net/johndoe" type="url" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="block relative mb-8" data-cid="n316">
                  <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n317">
                    Upload Resume *
                  </label>
                  {" "}
                  <div className="border-2 border-dashed border-surface-2 block relative p-8 text-center cursor-pointer" data-cid="n318">
                    {" "}
                    <div className="block mb-3 text-primary text-[2rem] leading-[2.4375rem]" data-cid="n319">
                      <i className="inline-block [font-family:'Font_Awesome_6_Free'] font-black leading-8 before:content-[''] before:text-primary before:text-[2rem] before:font-black before:leading-8 before:text-center" data-cid="n320" />
                    </div>
                    {" "}
                    <div className="block text-color-001 text-sm leading-[1.0625rem]" data-cid="n321">
                      {"Drag & drop your resume here or click to browse"}
                    </div>
                    {" "}
                    <div className="block mt-2 text-sm font-semibold leading-4" data-cid="n322">
                      PDF, DOC, DOCX (Max 5MB)
                    </div>
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
                <div className="block relative mb-8" data-cid="n323">
                  <label className="block mb-2 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.2px] uppercase cursor-default" data-cid="n324" htmlFor="apply-message">
                    Cover Letter / Message *
                  </label>
                  {" "}
                  <textarea className="w-full h-[6.6875rem] border border-solid border-surface-2 inline-block py-[0.9rem] px-[1.2rem] overflow-auto text-[0.9375rem] leading-[1.1875rem] whitespace-pre-wrap [overflow-wrap:break-word] bg-color-010 cursor-text" data-cid="n325" data-component="textarea" id="apply-message" name="message" placeholder="Tell us why you want to join Focus VFX..." />
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <button className="w-full h-13.5 border border-solid border-clr-4 inline-flex relative z-1 mt-4 p-4 rounded-[50px] justify-center items-center overflow-hidden text-background font-bold tracking-[1.6px] text-center uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n326" data-component="button" type="submit">
                {" SUBMIT APPLICATION "}
                <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] font-black leading-4 before:content-[''] before:text-background before:text-base before:font-black before:leading-4 before:tracking-[1.6px] before:text-center" data-cid="n327" />
                {" "}
              </button>
              {" "}
            </form>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <div className="block" data-cid="n328" id="footer-placeholder">
        <footer className="border-t border-solid border-t-border block relative z-10 pt-20 pb-8 bg-background" data-cid="n329" id="site-footer">
          <div className="block max-w-320 px-8 max-lg:max-w-full 2xl:mx-80" data-cid="n330">
            <div className="grid mb-16 gap-12 grid-cols-[357.328px_178.672px_214.391px_321.609px] max-lg:gap-10 max-lg:text-center max-lg:grid-cols-1" data-cid="n331">
              <div className="flex flex-col max-lg:items-center" data-cid="n332">
                <a className="h-26 block cursor-pointer" data-cid="n333" data-component="link" href="/index.html">
                  {" "}
                  <img className="w-46.5 h-20 block max-w-full mb-6 overflow-clip [filter:drop-shadow(var(--clr-0)_0px_0px_5px)]" data-cid="n334" data-component="image" alt="Focus VFX Studio" src="/assets/cloned/images/f068e3c48022.png" />
                  {" "}
                </a>
                {" "}
                <p className="block mb-6 text-color-001 text-sm leading-[1.4375rem]" data-cid="n335">
                  {" Delivering premium Hollywood-grade Visual Effects, CGI, Motion Graphics, and Post Production solutions for films, advertising agencies, and corporate clients globally. "}
                </p>
                {" "}
                <div className="block mb-6" data-cid="n336">
                  <img className="w-45 h-30 block max-w-full overflow-clip max-md:w-[5.1875rem] max-md:h-[3.4375rem] md:max-lg:w-[6.5625rem] md:max-lg:h-17.5" data-cid="n337" data-component="image" alt="TPN Certified" src="/assets/cloned/images/b6106541035f.png" title="TPN Global Certified" />
                  {" "}
                </div>
                {" "}
                <div className="flex gap-[0.8rem] max-lg:justify-center" data-cid="n338">
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n339" data-component="link" aria-label="Instagram" href="https://www.instagram.com/focusvfx.official?igsh=b2xrNXBrMWU4emc5" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n340" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n341" data-component="link" aria-label="Facebook" href="https://www.facebook.com/share/1DC53weRmh/?mibextid=wwXIfr" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n342" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n343" data-component="link" aria-label="LinkedIn" href="https://www.linkedin.com/company/focus-vfx-pvt-ltd/" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n344" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n345" data-component="link" aria-label="X (Twitter)" href={"https://x.com/focus_vfx?s=21&t=uCjnNgro9kkL-sZe8yA5Bw"} target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n346" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n347" data-component="link" aria-label="Vimeo" href={"https://vimeo.com/user193282489?fl=pp&fe=sh"} target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n348" />
                  </a>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n349">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[148.7px] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n350" data-component="heading">
                  Quick Links
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n351">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n362">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[11.525rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n363" data-component="heading">
                  VFX Services
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n364">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col max-lg:items-center" data-cid="n387">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[18.225rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-lg:after:right-[5.825rem]" data-cid="n388" data-component="heading">
                  Studio Info
                </h4>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n389">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n390" />
                  {" "}
                  <span className="block" data-cid="n391">
                    No.33, Balammal Building,
                    <br className="inline" data-cid="n392" />
                    Burkit Road, T. Nagar,
                    <br className="inline" data-cid="n393" />
                    Chennai - 600017
                  </span>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n394">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n395" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n396" data-component="link" href="tel:+918925902036">
                    +91 8925902036
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n397">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n398" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n399" data-component="link" href="mailto:info@focusvfx.in">
                    info@focusvfx.in
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n400">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n401" />
                  {" "}
                  <span className="block" data-cid="n402">
                    Mon - Sat: 09:00 AM - 06:00 PM
                  </span>
                  {" "}
                </p>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="border-t border-solid border-t-border flex pt-8 flex-wrap justify-between items-center gap-4" data-cid="n403">
              <p className="block text-color-001 text-sm leading-4" data-cid="n404">
                {"© "}
                <span className="inline" data-cid="n405" id="copyright-year">
                  2026
                </span>
                {" Focus VFX Studio. All Rights Reserved."}
              </p>
              {" "}
              <p className="block text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[1.36px] uppercase" data-cid="n406">
                Crafting Visual Wonders Beyond Imagination
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
      <div className="w-2 h-2 block fixed top-[313.1rem] left-0 z-10000 rounded-[50%] bg-primary transform-[matrix(1,0,0,1,-4,-4)] pointer-events-none max-lg:hidden 2xl:top-px 2xl:left-px" data-cid="n407" />
      <div className="w-8 h-8 border border-solid border-color-004 block fixed top-0 left-0 z-10000 rounded-[50%] transform-[matrix(1,0,0,1,-16,-16)] pointer-events-none max-lg:hidden 2xl:top-px 2xl:left-px" data-cid="n408" />
    </>
  );
}
