import "./ditto.css";
import DittoWire from "./ditto/DittoWire";
import CoverflowCarousel from "./components/coverflow-carousel";
import Logo from "./components/logo";
import Tile from "./components/tile";
import Tile2 from "./components/tile2";
import MediaCard from "./components/media-card";
import MediaCard2 from "./components/media-card2";
import FeatureCard from "./components/feature-card";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
import VideoModal from "./components/video-modal";
// Generated by clone-site. Do not edit by hand.
const Logo_data = [
  { alt: "Poster 1", imgSrc: "/assets/cloned/images/09fb9509c5d4.jpg", alt2: "Poster 2", imgSrc2: "/assets/cloned/images/0ae69df7bc52.jpeg", alt3: "Poster 3", imgSrc3: "/assets/cloned/images/bdcdb38e6ebf.jpg", alt4: "Poster 4", imgSrc4: "/assets/cloned/images/b2b66908cd9c.jfif", alt5: "Poster 1", imgSrc5: "/assets/cloned/images/09fb9509c5d4.jpg", alt6: "Poster 2", imgSrc6: "/assets/cloned/images/0ae69df7bc52.jpeg", alt7: "Poster 3", imgSrc7: "/assets/cloned/images/bdcdb38e6ebf.jpg", alt8: "Poster 4", imgSrc8: "/assets/cloned/images/b2b66908cd9c.jfif" },
  { alt: "Poster 5", imgSrc: "/assets/cloned/images/f33d2accbf0d.jpeg", alt2: "Poster 6", imgSrc2: "/assets/cloned/images/e750aa313d6a.jpeg", alt3: "Poster 7", imgSrc3: "/assets/cloned/images/roto.jpeg", alt4: "Poster 8", imgSrc4: "/assets/cloned/images/prep.jpg", alt5: "Poster 5", imgSrc5: "/assets/cloned/images/f33d2accbf0d.jpeg", alt6: "Poster 6", imgSrc6: "/assets/cloned/images/e750aa313d6a.jpeg", alt7: "Poster 7", imgSrc7: "/assets/cloned/images/roto.jpeg", alt8: "Poster 8", imgSrc8: "/assets/cloned/images/prep.jpg" },
  { alt: "Poster 9", imgSrc: "/assets/cloned/images/comp.jpeg", alt2: "Poster 10", imgSrc2: "/assets/cloned/images/e69013e6b001.jpg", alt3: "Poster 11", imgSrc3: "/assets/cloned/images/3df29ff21bd4.jpeg", alt4: "Poster 12", imgSrc4: "/assets/cloned/images/05afddd9f1d4.jpeg", alt5: "Poster 9", imgSrc5: "/assets/cloned/images/comp.jpeg", alt6: "Poster 10", imgSrc6: "/assets/cloned/images/e69013e6b001.jpg", alt7: "Poster 11", imgSrc7: "/assets/cloned/images/3df29ff21bd4.jpeg", alt8: "Poster 12", imgSrc8: "/assets/cloned/images/05afddd9f1d4.jpeg" }
];
const Tile_data = [
  { kind: "image", alt: "Poster 13", imgSrc: "/assets/cloned/images/6f18599fda9f.jpeg" },
  { kind: "image", alt: "Poster 14", imgSrc: "/assets/cloned/images/49eaabbfe89a.jpg" },
  { kind: "image", alt: "Poster 15", imgSrc: "/assets/cloned/images/58cd37376202.jpg" },
  { alt: "Poster 16", imgSrc: "/assets/cloned/images/67e53db6a0b7.jpg" },
  { alt: "Poster 13", imgSrc: "/assets/cloned/images/6f18599fda9f.jpeg" },
  { alt: "Poster 14", imgSrc: "/assets/cloned/images/49eaabbfe89a.jpg" }
];
const Tile2_data = [
  { text: "120", text2: "PROJECTS WORKED" },
  { text: "13", text2: "YEARS EXPERIENCE" },

];
const MediaCard_data = [
  { alt: "PREP", imgSrc: "/assets/cloned/images/prep.jpg", title: "PREP", description: "Laying the perfect foundation with storyboarding, concept art, and previz.\n            " },
  { alt: "COMPOSITING", imgSrc: "/assets/cloned/images/comp.jpeg", title: "COMPOSITING", description: "Pushing boundaries with photorealistic FX, digital environments and\n              compositing." },
  { alt: "ROTO", imgSrc: "/assets/cloned/images/roto.jpeg", title: "ROTO", description: "Breathing life into characters with state-of-the-art rigging and modeling.\n            " }
];
const MediaCard2_data = [
  { ariaLabel: "5 / 19", alt: "Andhra King", id: "card-img-andhra-king-4", imgSrc: "/assets/cloned/images/e69013e6b001.jpg", title: "Andhra King", description: "A high-octane political comedy tracking the chaotic journey of a fanatic fan turned regional hero.", text: "ROTO", text2: "CGI Production", text3: "Compositing" },
  { ariaLabel: "6 / 19", alt: "Madness (Bandhal)", id: "card-img-madness-5", imgSrc: "/assets/cloned/images/comp.jpeg", title: "Madness (Bandhal)", description: "A high-octane comedy-thriller featuring Mohanlal and Dileep in a roller-coaster ride of action, suspense, and chaos.", text: "ROTO", text2: "CGI Production", text3: "3D Animation" },
  { ariaLabel: "7 / 19", alt: "Thalaivar Thambi Thalaimaiyil (TTT)", id: "card-img-ttt-6", imgSrc: "/assets/cloned/images/324f06153260.jpg", title: "Thalaivar Thambi Thalaimaiyil (TTT)", description: "A compelling political drama outlining the rebellion of rural citizens under the leadership of a charismatic town leader.", text: "Crowd Multiplication", text2: "Matte Painting", text3: "Compositing" },
  { ariaLabel: "8 / 19", alt: "Parasakthi", id: "card-img-parasakthi-7", imgSrc: "/assets/cloned/images/67e53db6a0b7.jpg", title: "Parasakthi", description: "A visually magnificent romance directed by Sudha Kongara, telling a story of passion, trials, and cinematic beauty.", text: "ROTO", text2: "Matte Painting", text3: "Compositing" },
  { ariaLabel: "9 / 19", alt: "Bloody Beggar", id: "card-img-bloody-beggar-8", imgSrc: "/assets/cloned/images/f33d2accbf0d.jpeg", title: "Bloody Beggar", description: "A dark comedy thriller that turns the tale of a beggar into an intense mystery.", text: "ROTO", text2: "Color Grading", text3: "Compositing" },
  { ariaLabel: "10 / 19", alt: "Ghaati", id: "card-img-ghaati-9", imgSrc: "/assets/cloned/images/05afddd9f1d4.jpeg", title: "Ghaati", description: "A rustic action drama set in a rugged landscape with breathtaking visuals.", text: "Matte Painting", text2: "ROTO", text3: "CGI Production" },
  { ariaLabel: "11 / 19", alt: "Indian 2", id: "card-img-indian-2-10", imgSrc: "/assets/cloned/images/0ae69df7bc52.jpeg", title: "Indian 2", description: "The return of Senapathy in an epic vigilante action film.", text: "De-aging", text2: "Crowd Multiplication", text3: "ROTO" },
  { ariaLabel: "12 / 19", alt: "Loveli", id: "card-img-loveli-11", imgSrc: "/assets/cloned/images/6f18599fda9f.jpeg", title: "Loveli", description: "A heart-touching romantic musical exploring the depths of modern relationships.", text: "Color Grading", text2: "Compositing", text3: "Digital Cleanup" },
  { ariaLabel: "13 / 19", alt: "Rathnam", id: "card-img-rathnam-12", imgSrc: "/assets/cloned/images/3df29ff21bd4.jpeg", title: "Rathnam", description: "An intense action movie packed with adrenaline-pumping sequences.", text: "Wire Removal", text2: "Blood Enhancements", text3: "ROTO" },
  { ariaLabel: "14 / 19", alt: "TK", id: "card-img-tk-13", imgSrc: "/assets/cloned/images/prep.jpg", title: "TK", description: "A gripping thriller that keeps you on the edge of your seat.", text: "Compositing", text2: "ROTO", text3: "Color Grading" },
  { ariaLabel: "15 / 19", alt: "Turbo", id: "card-img-turbo-14", imgSrc: "/assets/cloned/images/roto.jpeg", title: "Turbo", description: "A fast-paced action comedy led by Mammootty.", text: "ROTO", text2: "CGI Production", text3: "Compositing" },
  { ariaLabel: "16 / 19", alt: "Thangalaan", id: "card-img-thangalaan-15", imgSrc: "/assets/cloned/images/e750aa313d6a.jpeg", title: "Thangalaan", description: "A historical action film set against the backdrop of the Kolar Gold Fields.", text: "Environment Generation", text2: "Creature CGI", text3: "ROTO" },
  { ariaLabel: "17 / 19", alt: "Thug Life", id: "card-img-thug-life-16", imgSrc: "/assets/cloned/images/b2b66908cd9c.jfif", title: "Thug Life", description: "A highly anticipated epic action drama starring Kamal Haasan.", text: "ROTO", text2: "Compositing", text3: "CGI Production" }
];
const FeatureCard_data = [
  { title: "Creative Excellence", description: "Pushing the boundaries of ROTO to deliver artistic visuals that tell\n            powerful stories." },
  { title: "On-Time Delivery", description: "Robust scheduling and pipeline management ensuring deadlines are met, every time." },
  { title: "Premium Quality", description: "Uncompromised pixel quality with strict validation standards for multi-screen\n            projection." },
  { title: "Client Satisfaction", description: "Collaborating closely with directors and producers to bring their vision to absolute\n            life." }
];
const ListRow_data = [
  { href: "/index.html", label: "Home" },
  { href: "/about.html", label: "About Us" },
  { href: "/works.html", label: "Our Works" },
  { href: "/career.html", label: "Careers" },
  { href: "/contact.html", label: "Contact Us" }
];
const ListRow2_data = [
  { label: "PREP" },
  { label: "Compositing" },
  { label: "ROTO" },
  { label: "Matchmovie" },
  { label: "Digital Cleanup" }
];
const Logo_cids: string[][] = [
  ["n25", "n26", "n27", "n28", "n29", "n30", "n31", "n32", "n33"],
  ["n34", "n35", "n36", "n37", "n38", "n39", "n40", "n41", "n42"],
  ["n43", "n44", "n45", "n46", "n47", "n48", "n49", "n50", "n51"]
];
const Tile_cids: string[][] = [
  ["n53"],
  ["n54"],
  ["n55"],
  ["n56"],
  ["n57"],
  ["n58"]
];
const Tile2_cids: string[][] = [
  ["n112", "n113", "n114", "n115"],
  ["n116", "n117", "n118", "n119"],
  ["n120", "n121", "n122", "n123"]
];
const MediaCard_cids: string[][] = [
  ["n131", "n132", "n133", "n134", "n135", "n136", "n137"],
  ["n138", "n139", "n140", "n141", "n142", "n143", "n144"],
  ["n145", "n146", "n147", "n148", "n149", "n150", "n151"]
];
const MediaCard2_cids: string[][] = [
  ["n276", "n277", "n278", "n279", "n280", "n282", "n283", "n284", "n285", "n286", "n287", "n288", "n289", "n290", "n291", "n292", "n293", "n294"],
  ["n295", "n296", "n297", "n298", "n299", "n301", "n302", "n303", "n304", "n305", "n306", "n307", "n308", "n309", "n310", "n311", "n312", "n313"],
  ["n314", "n315", "n316", "n317", "n318", "n320", "n321", "n322", "n323", "n324", "n325", "n326", "n327", "n328", "n329", "n330", "n331", "n332"],
  ["n333", "n334", "n335", "n336", "n337", "n339", "n340", "n341", "n342", "n343", "n344", "n345", "n346", "n347", "n348", "n349", "n350", "n351"],
  ["n352", "n353", "n354", "n355", "n356", "n358", "n359", "n360", "n361", "n362", "n363", "n364", "n365", "n366", "n367", "n368", "n369", "n370"],
  ["n371", "n372", "n373", "n374", "n375", "n377", "n378", "n379", "n380", "n381", "n382", "n383", "n384", "n385", "n386", "n387", "n388", "n389"],
  ["n390", "n391", "n392", "n393", "n394", "n396", "n397", "n398", "n399", "n400", "n401", "n402", "n403", "n404", "n405", "n406", "n407", "n408"],
  ["n409", "n410", "n411", "n412", "n413", "n415", "n416", "n417", "n418", "n419", "n420", "n421", "n422", "n423", "n424", "n425", "n426", "n427"],
  ["n428", "n429", "n430", "n431", "n432", "n434", "n435", "n436", "n437", "n438", "n439", "n440", "n441", "n442", "n443", "n444", "n445", "n446"],
  ["n447", "n448", "n449", "n450", "n451", "n453", "n454", "n455", "n456", "n457", "n458", "n459", "n460", "n461", "n462", "n463", "n464", "n465"],
  ["n466", "n467", "n468", "n469", "n470", "n472", "n473", "n474", "n475", "n476", "n477", "n478", "n479", "n480", "n481", "n482", "n483", "n484"],
  ["n485", "n486", "n487", "n488", "n489", "n491", "n492", "n493", "n494", "n495", "n496", "n497", "n498", "n499", "n500", "n501", "n502", "n503"],
  ["n504", "n505", "n506", "n507", "n508", "n510", "n511", "n512", "n513", "n514", "n515", "n516", "n517", "n518", "n519", "n520", "n521", "n522"]
];
const FeatureCard_cids: string[][] = [
  ["n551", "n552", "n553", "n554", "n555"],
  ["n556", "n557", "n558", "n559", "n560"],
  ["n561", "n562", "n563", "n564", "n565"],
  ["n566", "n567", "n568", "n569", "n570"],
  ["n571", "n572", "n573", "n574", "n575"],
  ["n576", "n577", "n578", "n579", "n580"]
];
const ListRow_cids: string[][] = [
  ["n625", "n626"],
  ["n627", "n628"],
  ["n629", "n630"],
  ["n631", "n632"],
  ["n633", "n634"]
];
const ListRow2_cids: string[][] = [
  ["n638", "n639"],
  ["n640", "n641"],
  ["n642", "n643"],
  ["n644", "n645"],
  ["n646", "n647"],
  ["n648", "n649"],
  ["n650", "n651"],
  ["n652", "n653"],
  ["n654", "n655"],
  ["n656", "n657"],
  ["n658", "n659"]
];
const Logo_styles = [
  { className: "[animation-name:scrollDown]" },
  { className: "[animation-name:scrollUp]" },
  { className: "[animation-name:scrollDown]" }
];
const Tile2_styles = [
  {},
  { className: "whitespace-nowrap" },
  {}
];
const MediaCard_styles = [
  { className: "origin-[193.664px_258.547px] 2xl:origin-[213.664px_285.219px]" },
  { className: "origin-[193.664px_258.547px] 2xl:origin-[213.664px_285.219px]" },
  { className: "origin-[193.672px_258.562px] 2xl:origin-[213.672px_285.227px]" }
];
const MediaCard2_styles = [
  { className: "-z-3 transform-[matrix3d(-0.5,0,0.866025,0,0,1,0,0,-0.866025,0,-0.5,0,0,0,-1000,1)] max-md:transform-[matrix3d(-0.499733,0,0.866179,0,0,1,0,0,-0.866179,0,-0.499733,0,0,0,-999.853,1)] md:max-lg:transform-[matrix3d(-0.500201,0,0.86591,0,0,1,0,0,-0.86591,0,-0.500201,0,0,0,-1000.11,1)]", className2: "max-md:h-auto", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-4 transform-[matrix3d(-0.866025,0,0.5,0,0,1,0,0,-0.5,0,-0.866025,0,0,0,-1250,1)] max-md:transform-[matrix3d(-0.866247,0,0.499617,0,0,1,0,0,-0.499617,0,-0.866247,0,0,0,-1250.21,1)] md:max-lg:transform-[matrix3d(-0.866249,0,0.499613,0,0,1,0,0,-0.499613,0,-0.866249,0,0,0,-1250.21,1)]", className3: "max-md:h-auto", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-5 transform-[matrix3d(-1,0,0,0,0,1,0,0,0,0,-1,0,0,0,-1500,1)] max-md:transform-[matrix3d(-0.999999,0,-0.00119301,0,0,1,0,0,0.00119301,0,-0.999999,0,0,0,-1500.57,1)] md:max-lg:transform-[matrix3d(-1,0,0.000399501,0,0,1,0,0,-0.000399501,0,-1,0,0,0,-1499.81,1)]", className3: "max-md:h-24", className4: "h-[1.125rem]" },
  { className: "-z-6 transform-[matrix3d(-0.866025,0,-0.5,0,0,1,0,0,0.5,0,-0.866025,0,0,0,-1750,1)] max-md:transform-[matrix3d(-0.866256,0,-0.4996,0,0,1,0,0,0.4996,0,-0.866256,0,0,0,-1749.78,1)] md:max-lg:transform-[matrix3d(-0.866117,0,-0.499841,0,0,1,0,0,0.499841,0,-0.866117,0,0,0,-1749.91,1)]", className4: "h-[1.125rem]" },
  { className: "-z-7 transform-[matrix3d(-0.5,0,-0.866025,0,0,1,0,0,0.866025,0,-0.5,0,0,0,-2000,1)] max-md:transform-[matrix3d(-0.49975,0,-0.86617,0,0,1,0,0,0.86617,0,-0.49975,0,0,0,-2000.14,1)] md:max-lg:transform-[matrix3d(-0.499972,0,-0.866041,0,0,1,0,0,0.866041,0,-0.499972,0,0,0,-2000.02,1)]", className3: "max-md:h-auto", className5: "h-[1.3375rem] max-lg:h-auto" },
  { className: "-z-8 transform-[matrix3d(0,0,-1,0,0,1,0,0,1,0,0,0,0,0,-2250,1)] max-md:transform-[matrix3d(0.00103908,0,-0.999999,0,0,1,0,0,0.999999,0,0.00103908,0,0,0,-2250.5,1)] md:max-lg:transform-[matrix3d(0.000247563,0,-1,0,0,1,0,0,1,0,0.000247563,0,0,0,-2250.12,1)]" },
  { className: "-z-9 transform-[matrix3d(0.5,0,-0.866025,0,0,1,0,0,0.866025,0,0.5,0,0,0,-2500,1)] max-md:transform-[matrix3d(0.499467,0,-0.866333,0,0,1,0,0,0.866333,0,0.499467,0,0,0,-2499.71,1)] md:max-lg:transform-[matrix3d(0.500401,0,-0.865794,0,0,1,0,0,0.865794,0,0.500401,0,0,0,-2500.22,1)]", className4: "h-[1.125rem]" },
  { className: "-z-10 transform-[matrix3d(0.866025,0,-0.5,0,0,1,0,0,0.5,0,0.866025,0,0,0,-2750,1)] max-md:transform-[matrix3d(0.866093,0,-0.499883,0,0,1,0,0,0.499883,0,0.866093,0,0,0,-2750.06,1)] md:max-lg:transform-[matrix3d(0.865834,0,-0.500332,0,0,1,0,0,0.500332,0,0.865834,0,0,0,-2749.82,1)]", className4: "h-[1.125rem]" },
  { className: "-z-11 transform-[matrix3d(1,0,0,0,0,1,0,0,0,0,1,0,0,0,-3000,1)] max-md:transform-[matrix3d(1,0,0.00088514,0,0,1,0,0,-0.00088514,0,1,0,0,0,-3000.42,1)] md:max-lg:transform-[matrix3d(1,0,-0.000167876,0,0,1,0,0,0.000167876,0,1,0,0,0,-2999.92,1)]", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-12 transform-[matrix3d(0.866025,0,0.5,0,0,1,0,0,-0.5,0,0.866025,0,0,0,-3250,1)] max-md:transform-[matrix3d(0.86641,0,0.499333,0,0,1,0,0,-0.499333,0,0.86641,0,0,0,-3249.63,1)] md:max-lg:transform-[matrix3d(0.866001,0,0.500041,0,0,1,0,0,-0.500041,0,0.866001,0,0,0,-3250.02,1)]", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-13 transform-[matrix3d(0.5,0,0.866025,0,0,1,0,0,-0.866025,0,0.5,0,0,0,-3500,1)] max-md:transform-[matrix3d(0.500017,0,0.866016,0,0,1,0,0,-0.866016,0,0.500017,0,0,0,-3499.99,1)] md:max-lg:transform-[matrix3d(0.499772,0,0.866157,0,0,1,0,0,-0.866157,0,0.499772,0,0,0,-3500.13,1)]", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-14 transform-[matrix3d(0,0,1,0,0,1,0,0,-1,0,0,0,0,0,-3750,1)] max-md:transform-[matrix3d(-0.000731203,0,1,0,0,1,0,0,-1,0,-0.000731203,0,0,0,-3750.35,1)] md:max-lg:transform-[matrix3d(-0.000479189,0,1,0,0,1,0,0,-1,0,-0.000479189,0,0,0,-3750.23,1)]", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" },
  { className: "-z-15 transform-[matrix3d(-0.5,0,0.866025,0,0,1,0,0,-0.866025,0,-0.5,0,0,0,-4000,1)] max-md:transform-[matrix3d(-0.4992,0,0.866487,0,0,1,0,0,-0.866487,0,-0.4992,0,0,0,-3999.56,1)] md:max-lg:transform-[matrix3d(-0.499682,0,0.866209,0,0,1,0,0,-0.866209,0,-0.499682,0,0,0,-3999.82,1)]", className4: "h-[1.125rem]", className5: "h-[1.3375rem]", className6: "h-[1.3375rem]", className7: "h-[1.3375rem]" }
];
const FeatureCard_styles = [
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" },
  { className: "before:content-['']" }
];

export default function Page() {
  return (
    <>
      <section className="h-200 min-h-screen flex relative items-center overflow-hidden bg-background max-md:h-203 max-lg:pt-24 md:max-lg:h-256 2xl:h-270" data-cid="n22" id="home">
        <div className="h-full block absolute top-0 inset-x-0 z-0 min-w-0 overflow-hidden bg-color-011" data-cid="n23">
          <div className="w-416 h-300 flex absolute -top-30 z-0 opacity-35 gap-6 transform-[matrix(1.08329,-0.191013,0.191013,1.08329,0,0)] origin-[832px_600px] max-md:w-[487.5px] max-md:h-304.5 max-md:-top-[7.6125rem] max-md:origin-[243.75px_609px] md:max-lg:w-[62.4rem] md:max-lg:h-384 md:max-lg:-top-[9.6rem] md:max-lg:origin-[499.195px_768px] 2xl:w-624 2xl:h-405 2xl:-top-40.5 2xl:origin-[1248px_810px]" data-cid="n24">
            {Logo_data.map((d, i) => <Logo key={i} d={d} cids={Logo_cids[i]} styles={Logo_styles[i]} />)}
            {" "}
            <div className="w-99.5 h-300 flex flex-col gap-6 [animation-name:scrollUp] [animation-duration:40s] [animation-timing-function:linear] [animation-iteration-count:infinite] max-md:w-[103.9px] max-md:h-304.5 md:max-lg:w-[14.475rem] md:max-lg:h-384 2xl:w-151.5 2xl:h-405" data-cid="n52">
              {Tile_data.map((d, i) => <Tile key={i} d={d} cids={Tile_cids[i]} />)}
              {" "}
            </div>
            {" "}
          </div>
          {" "}
          <div className="w-384 h-240 block absolute -top-20 -left-32 z-1 opacity-[0.61687] [mix-blend-mode:screen] [background-size:auto,_auto] [background-position:0%_0%,_0%_0%] [background-repeat:repeat,_repeat] [background-clip:border-box,_border-box] [background-origin:padding-box,_padding-box] [background-attachment:scroll,_scroll] [background-blend-mode:normal,_normal] [filter:blur(60px)] [-webkit-background-clip:border-box,_border-box] [animation-name:volumetricPulse] [animation-duration:6s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] pointer-events-none max-md:w-112.5 max-md:h-[60.9rem] max-md:-top-[5.075rem] max-md:left-[-37.5px] md:max-lg:w-[57.6rem] md:max-lg:h-[76.8rem] md:max-lg:-top-[6.4rem] md:max-lg:-left-[4.8rem] 2xl:w-576 2xl:h-324 2xl:-top-27 2xl:-left-48" style={{ backgroundImage: "radial-gradient(at 70% 40%, var(--clr-3) 0%, var(--clr-4) 60%), radial-gradient(at 20% 80%, var(--clr-5) 0%, var(--clr-4) 50%)" }} data-cid="n59" />
          {" "}
          <img className="w-320 h-200 block absolute z-1 overflow-clip aspect-[auto_1280/800] pointer-events-none max-md:w-[23.4375rem] max-md:h-203 max-md:aspect-[auto_375/812] md:max-lg:w-192 md:max-lg:h-256 md:max-lg:aspect-[auto_768/1024] 2xl:w-480 2xl:h-270 2xl:aspect-[auto_1920/1080]" data-cid="n60" height="800" id="hero-particles" src="/assets/cloned/images/5bd24ab131a8.png" width="1280" alt="" />
          {" "}
          <div className="w-320 h-200 block absolute top-0 left-0 z-1 opacity-[0.994226] [background-size:auto,_auto] [background-position:0%_0%,_0%_0%] [background-repeat:repeat,_repeat] [background-clip:border-box,_border-box] [background-origin:padding-box,_padding-box] [background-attachment:scroll,_scroll] [background-blend-mode:normal,_normal] [-webkit-background-clip:border-box,_border-box] [animation-name:smokeFloat] [animation-duration:8s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] [animation-direction:alternate] pointer-events-none max-md:w-[23.4375rem] max-md:h-203 md:max-lg:w-192 md:max-lg:h-256 2xl:w-480 2xl:h-270" style={{ backgroundImage: "radial-gradient(circle at 80% 50%, var(--clr-5) 0%, var(--clr-4) 50%), radial-gradient(circle at 10% 60%, var(--border) 0%, var(--clr-4) 40%)" }} data-cid="n61" />
          {" "}
          <img className="w-320 h-200 block absolute opacity-50 overflow-clip aspect-[auto_1280/800] max-md:w-[23.4375rem] max-md:h-203 max-md:aspect-[auto_375/812] md:max-lg:w-192 md:max-lg:h-256 md:max-lg:aspect-[auto_768/1024] 2xl:w-480 2xl:h-270 2xl:aspect-[auto_1920/1080]" data-cid="n62" aria-hidden="true" height="800" id="three-canvas" src="/assets/cloned/images/564865e47836.png" width="1280" alt="" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 z-2 pointer-events-none" style={{ backgroundImage: "linear-gradient(135deg, var(--clr-6) 0%, var(--clr-7) 40%, var(--clr-6) 100%)" }} data-cid="n63" />
          {" "}
        </div>
        {" "}
        <div className="w-full block relative z-3 max-w-350 pt-32 pb-16 px-16 mx-auto" data-cid="n64">
          <div className="w-full max-w-237.5 block" data-cid="n65">
            <span className="border border-solid border-color-009 inline-block mb-6 py-[0.4rem] px-4 rounded-[50px] text-primary [font-family:Outfit,_sans-serif] text-xs font-bold leading-[0.9375rem] tracking-[3.6px] uppercase" data-cid="n66">
              Quality Is Our First Motive
            </span>
            {" "}
            <h1 className="flex mb-8 flex-col text-[2rem] font-black leading-8 tracking-[-0.64px] uppercase max-md:text-[1.8125rem] max-md:leading-[1.8125rem] max-md:tracking-[0.58px] md:max-lg:text-[2.1875rem] md:max-lg:leading-[2.1875rem] md:max-lg:tracking-[0.7px]" data-cid="n67" data-component="heading">
              <span className="block text-[4.8125rem] leading-[4.8125rem] max-md:text-[2.5rem] max-md:leading-10 md:max-lg:text-[2.875rem] md:max-lg:leading-[2.875rem] 2xl:text-8xl 2xl:leading-24" data-cid="n68">
                {" "}
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n69">
                  A
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n70">
                  J
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n71">
                  I
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n72">
                  T
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n73">
                  H
                </span>

                {" "}
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n75">
                  K
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n76">
                  U
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n77">
                  M
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n78">
                  A
                </span>
                <span className="inline-block whitespace-pre text-nowrap" data-cid="n79">
                  R
                </span>
                <span className="inline-block text-primary whitespace-nowrap text-nowrap [text-shadow:var(--clr-8)_0px_0px_20px,_var(--clr-9)_0px_0px_45px]" data-cid="n89">
                  <span className="inline-block whitespace-pre" data-cid="n90">
                    P
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n91">
                    O
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n92">
                    R
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n93">
                    T
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n94">
                    F
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n95">
                    O
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n96">
                    L
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n97">
                    I
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n98">
                    O
                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n99">

                  </span>
                  <span className="inline-block whitespace-pre" data-cid="n100">

                  </span>
                </span>
                {" "}
              </span>
              {" "}
            </h1>
            {" "}
            <div className="flex flex-wrap gap-4" data-cid="n102">
              <a className="w-[211.5px] h-[2.5625rem] border border-solid border-clr-4 flex relative z-1 opacity-0 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] transform-[matrix(0.95,0,0,0.95,0,20)] origin-[105.742px_20.5px] cursor-pointer" data-cid="n103" href="/works.html">
                {"VIEW OUR WORK "}
                <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-background before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n104" />
              </a>
              {" "}
              <button className="w-[11.175rem] h-[2.5625rem] border border-solid border-surface-4 flex relative z-1 opacity-0 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-[0.8125rem] font-semibold leading-[0.9375rem] tracking-[1.28px] text-center uppercase transform-[matrix(0.95,0,0,0.95,0,20)] origin-[89.4062px_20.5px] cursor-pointer" data-cid="n105" id="hero-watch-reel">
                {"WATCH REEL "}
                <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] text-xs font-black leading-3 before:content-[''] before:text-foreground before:text-xs before:font-black before:leading-3 before:tracking-[1.28px] before:text-center" data-cid="n106" />
              </button>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
        <div className="w-[55.5px] h-[4.6875rem] flex absolute bottom-10 left-16 z-5 min-w-0 flex-col items-center gap-3 text-color-013 [font-family:Outfit,_sans-serif] text-[0.625rem] font-bold leading-[0.8125rem] tracking-[2.6px]" data-cid="n107">
          <span className="block" data-cid="n108">
            SCROLL
          </span>
          {" "}
          <div className="w-px h-12.5 block opacity-[0.815092] [animation-name:scrollPulse] [animation-duration:2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite]" style={{ backgroundImage: "linear-gradient(var(--color-013), var(--clr-4))" }} data-cid="n109" />
          {" "}
        </div>
        {" "}
      </section>
      <section className="border-b border-solid border-b-border block py-20 bg-color-011" data-cid="n110" id="stats">
        <div className="flex max-w-300 mx-auto px-8 flex-wrap justify-around gap-12" data-cid="n111">
          {Tile2_data.map((d, i) => <Tile2 key={i} d={d} cids={Tile2_cids[i]} styles={Tile2_styles[i]} />)}
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-32 bg-background max-lg:py-16" data-cid="n124" id="expertise">
        <div className="block max-w-350 px-8 mx-auto" data-cid="n125">
          <div className="flex mb-16 justify-between items-end" data-cid="n126">
            <h2 className="block text-[4rem] font-bold leading-[4.8125rem] tracking-[-1.28px] uppercase max-lg:text-[2.5rem] max-lg:leading-[3.0625rem] max-lg:tracking-[-0.8px]" data-cid="n127" data-component="heading">
              OUR EXPERTISE
            </h2>
            {" "}
            <a className="w-[200.7px] border border-solid border-surface-4 flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-[0.8125rem] font-semibold leading-[0.9375rem] tracking-[1.28px] uppercase cursor-pointer max-md:w-[99.5px] md:max-lg:w-[492.5px]" data-cid="n128" data-component="button" href="/contact.html">
              {"WORK WITH US "}
              <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-foreground before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n129" />
            </a>
            {" "}
          </div>
          {" "}
          <div className="grid gap-6 grid-cols-3 max-md:grid-cols-1 md:max-lg:grid-cols-2 2xl:grid-cols-[429.328px_429.328px_429.344px_0px]" data-cid="n130">
            {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} cids={MediaCard_cids[i]} styles={MediaCard_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-32 bg-background max-lg:py-16" data-cid="n152" id="works">
        <div className="block max-w-350 px-8 mx-auto" data-cid="n153">
          <div className="flex mb-16 justify-between items-end" data-cid="n154">
            <h2 className="block text-[4rem] font-bold leading-[4.8125rem] tracking-[-1.28px] uppercase max-lg:text-[2.5rem] max-lg:leading-[3.0625rem] max-lg:tracking-[-0.8px]" data-cid="n155" data-component="heading">
              LATEST WORK
            </h2>
            {" "}
            <a className="w-[12.9375rem] border border-solid border-surface-4 flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-[0.8125rem] font-semibold leading-[0.9375rem] tracking-[1.28px] uppercase cursor-pointer max-md:w-[163.3px] md:max-lg:w-[31.85rem]" data-cid="n156" data-component="button" href="/works.html">
              {"VIEW ALL WORK "}
              <i className="block ml-2 [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-foreground before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n157" />
            </a>
            {" "}
          </div>
          {" "}
          <div className="block relative z-1 py-12.5 overflow-hidden" data-cid="n158" id="home-works-swiper">
            <CoverflowCarousel items={[
              <MediaCard2 key="1" d={{ ariaLabel: "1 / 5", alt: "Dummy 1", id: "dummy-1", imgSrc: "/assets/cloned/images/dip.jpeg", title: "THE DIPLOMAT", description: "A gripping political thriller following an Indian diplomat as he navigates a high-stakes international mission to rescue an Indian citizen from Pakistan.", text: "VFX", text2: "3D", text3: "CG" }} cids={[]} styles={{} as any} />,
              <MediaCard2 key="2" d={{ ariaLabel: "2 / 5", alt: "Dummy 2", id: "dummy-2", imgSrc: "/assets/cloned/images/manju.jpeg", title: "manjummel boys", description: "A Malayalam survival thriller that chronicles a group of friends’ desperate attempt to save their companion trapped in a dangerous Chilean cave.", text: "VFX", text2: "3D", text3: "CG" }} cids={[]} styles={{} as any} />,
              <MediaCard2 key="3" d={{ ariaLabel: "3 / 5", alt: "Dummy 3", id: "dummy-3", imgSrc: "/assets/cloned/images/cib.jpeg", title: "CIBELES", description: "A psychological drama exploring the intertwined lives of a young woman, a detective, and a mysterious influencer as they navigate love, deception, and identity.", text: "VFX", text2: "3D", text3: "CG" }} cids={[]} styles={{} as any} />,
              <MediaCard2 key="4" d={{ ariaLabel: "4 / 5", alt: "Dummy 4", id: "dummy-4", imgSrc: "/assets/cloned/images/agni.jpeg", title: "AGNI", description: "A gripping action-thriller where a righteous cop leads a relentless crusade against a ruthless mafia kingpin, battling corruption and violence at every turn.", text: "VFX", text2: "3D", text3: "CG" }} cids={[]} styles={{} as any} />,
              <MediaCard2 key="5" d={{ ariaLabel: "5 / 5", alt: "Dummy 5", id: "dummy-5", imgSrc: "/assets/cloned/images/campa.jpeg", title: "The Goat Life", description: "A biographical drama based on the harrowing true story of Najeeb Muhammad, who was enslaved and forced to work as a camel herder in the Saudi desert.", text: "VFX", text2: "3D", text3: "CG" }} cids={[]} styles={{} as any} />
            ]} />
          </div>
          {" "}
        </div>
        {" "}

      </section>
      <section className="border-t border-solid border-t-border border-b border-b-border block relative py-32 bg-color-002 max-lg:py-16" data-cid="n545" id="why-us">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n546">
          <div className="block relative mb-16 text-center max-lg:mb-10" data-cid="n547">
            <span className="block mb-3 text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[3.6px]" data-cid="n548">
              AJITH KUMAR
            </span>
            {" "}
            <h2 className="inline-block relative [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[2px] uppercase max-md:text-[1.625rem] max-md:leading-[2.0625rem] max-md:tracking-[1.28px] md:max-lg:text-[1.8125rem] md:max-lg:leading-9 md:max-lg:tracking-[1.44px] after:content-[''] after:block after:absolute after:top-[3.5625rem] after:right-[9.9125rem] after:-bottom-2.5 after:left-[13.6625rem] after:w-15 after:h-[0.1875rem] after:bg-primary after:shadow-[var(--primary)_0px_0px_10px_0px] after:transform-[matrix(1,0,0,1,-30,0)] after:origin-[0px_1.5px] max-md:after:top-10 max-md:after:right-20 max-md:after:left-[139.9px] md:max-lg:after:top-[2.6875rem] md:max-lg:after:right-[6.0875rem] md:max-lg:after:left-[9.8375rem]" data-cid="n549" data-component="heading">
              STRENGTHS
            </h2>
            {" "}
          </div>
          {" "}
          <div className="grid gap-6 grid-cols-3 grid-rows-2 max-lg:grid-cols-1 max-lg:grid-rows-6" data-cid="n550">
            {FeatureCard_data.map((d, i) => <FeatureCard key={i} d={d} cids={FeatureCard_cids[i]} styles={FeatureCard_styles[i]} />)}
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="h-160 flex relative justify-center items-center overflow-hidden max-md:h-[40.6rem] md:max-lg:h-[51.2rem] 2xl:h-216" data-cid="n581" id="showreel">
        <div className="w-full h-full block absolute top-0 left-0 min-w-0 bg-cover [background-position:center_center] [filter:grayscale(0.6)_contrast(1.2)_brightness(0.7)]" style={{ backgroundImage: "url(\"/assets/cloned/images/agni.jpeg\")" }} data-cid="n582" />
        {" "}
        <div className="h-full block absolute top-0 inset-x-0 z-1 min-w-0 bg-color-008" data-cid="n583" />
        {" "}
        <div className="flex relative z-2 flex-col items-center justify-center text-center w-full h-full" data-cid="n584">
          <VideoModal videoUrl="https://player.vimeo.com/video/288006654">
            <button className="w-22.5 h-22.5 flex relative mb-8 rounded-[50%] justify-center items-center text-background [font-family:Arial] text-2xl leading-7 bg-primary shadow-[var(--clr-22)_0px_0px_40px_0px] cursor-pointer hover:scale-110 transition-transform duration-300" data-cid="n585" aria-label="Play Showreel" id="play-showreel-btn">
              <span className="block transform-[matrix(1,0,0,1,3,0)]" data-cid="n586">
                <i className="inline-block [font-family:'Font_Awesome_6_Free'] font-black leading-6 before:content-[''] before:text-background before:text-2xl before:font-black before:leading-6 before:text-center" data-cid="n587" />
              </span>
              {" "}
              <span className="w-22.5 h-7 border-2 border-solid border-primary block absolute top-0 left-0 -z-1 opacity-[0.69249] min-w-0 rounded-[50%] [animation-name:playRipple] [animation-duration:2s] [animation-timing-function:linear] [animation-iteration-count:infinite]" data-cid="n588" />
              {" "}
            </button>
          </VideoModal>
          {" "}
          <h3 className="block mb-3 text-5xl font-bold leading-[3.6875rem] tracking-[4.8px] uppercase max-md:text-[1.8125rem] max-md:leading-[2.1875rem] max-md:tracking-[2.88px] md:max-lg:text-[1.9375rem] md:max-lg:leading-[2.3125rem] md:max-lg:tracking-[3.07px]" data-cid="n589" data-component="heading">
            SHOWREEL
          </h3>
          {" "}
          <p className="block text-color-014 text-lg leading-[1.3125rem]" data-cid="n590">
            Experience our latest work in feature film and advertising.
          </p>
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative py-40 overflow-hidden text-center bg-color-011" data-cid="n591" id="cta">
        <div className="w-150 h-150 block absolute top-[308.1px] left-160 opacity-[0.598512] rounded-[50%] [filter:blur(40px)] [animation-name:orbPulse] [animation-duration:4s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] pointer-events-none max-md:top-82.5 max-md:left-[187.5px] md:max-lg:top-[19.025rem] md:max-lg:left-96 2xl:top-[22.875rem] 2xl:left-240" style={{ backgroundImage: "radial-gradient(circle, var(--clr-23) 0%, var(--clr-4) 70%)" }} data-cid="n592" />
        {" "}
        <div className="block relative z-2 max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n593">
          <h2 className="block relative z-2 mb-6 text-[4.8125rem] font-black leading-[5.0625rem] tracking-[-1.54px] uppercase max-md:text-[2.5rem] max-md:leading-10.5 max-md:tracking-[-0.8px] md:max-lg:text-[2.875rem] md:max-lg:leading-[3rem] md:max-lg:tracking-[-0.92px] 2xl:text-[5.5rem] 2xl:leading-[5.75rem] 2xl:tracking-[-1.76px]" data-cid="n594" data-component="heading">
            LET'S BUILD
            <br className="inline" data-cid="n595" />
            {" "}
            <span className="inline text-primary [text-shadow:var(--clr-24)_0px_0px_60px]" data-cid="n596">
              SOMETHING AMAZING TOGETHER
            </span>
          </h2>
          {" "}
          <p className="block relative z-2 mb-12 text-clr-25 text-lg leading-5.5" data-cid="n597">
            Have a project in mind? I'm ready to turn your ideas into stunning visuals. Let's create something that stands out.
          </p>
          {" "}
          <div className="flex flex-wrap justify-center gap-4 max-lg:flex-col" data-cid="n598">
            <a className="h-[2.5625rem] border border-solid border-clr-4 flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n599" data-component="button" href="/contact.html">
              START A PROJECT
            </a>
            {" "}
            <a className="h-[2.5625rem] border border-solid border-surface-3 flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-[0.8125rem] font-semibold leading-[0.9375rem] tracking-[1.28px] uppercase cursor-pointer" data-cid="n600" data-component="button" href="/works.html">
              VIEW OUR WORK
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <div className="block" data-cid="n601" id="footer-placeholder">
        <footer className="border-t border-solid border-t-border block relative z-10 pt-20 pb-8 bg-background" data-cid="n602" id="site-footer">
          <div className="block max-w-320 px-8 max-lg:max-w-full 2xl:mx-80" data-cid="n603">
            <div className="grid mb-16 gap-12 grid-cols-[357.328px_178.672px_214.391px_321.609px] max-lg:gap-10 max-lg:text-center max-lg:grid-cols-1" data-cid="n604">
              <div className="flex flex-col max-lg:items-center" data-cid="n605">
                <a className="h-26 block cursor-pointer" data-cid="n606" data-component="link" href="/index.html">
                  {" "}
                  <img className="w-46.5 h-20 block max-w-full mb-6 overflow-clip [filter:drop-shadow(var(--clr-0)_0px_0px_5px)]" data-cid="n607" data-component="image" alt="Focus VFX Studio" src="/assets/cloned/images/f068e3c48022.png" />
                  {" "}
                </a>
                {" "}
                <p className="block mb-6 text-color-001 text-sm leading-[1.4375rem]" data-cid="n608">
                  {" I specialize in delivering professional VFX solutions, including Prep, ROTO, Compositing, Matchmove, and Digital Cleanup. With a focus on quality, accuracy, and timely delivery, I help filmmakers, agencies, and creators bring every frame to life."}
                </p>
                {" "}
                <div className="block mb-6" data-cid="n609">
                  {" "}
                </div>
                {" "}
                <div className="flex gap-[0.8rem] max-lg:justify-center" data-cid="n611">
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n612" data-component="link" aria-label="Instagram" href="https://www.instagram.com/ajithkumarvfx/" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n613" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n614" data-component="link" aria-label="Facebook" href="https://www.facebook.com/ajithkumar.ajithkumar.50159" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n615" />
                  </a>
                  {" "}
                  <a className="w-9 h-9 border border-solid border-border flex rounded-[50%] justify-center items-center text-sm leading-4 bg-color-002 cursor-pointer" data-cid="n616" data-component="link" aria-label="LinkedIn" href="https://www.linkedin.com/in/ajithkumarlava/" target="_blank">
                    <i className="block [font-family:'Font_Awesome_6_Brands'] leading-[0.875rem] before:content-[''] before:text-foreground before:text-sm before:leading-[0.875rem] max-lg:before:text-center" data-cid="n617" />
                  </a>
                  {" "}
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n622">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[148.7px] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n623" data-component="heading">
                  Quick Links
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n624">
                  {ListRow_data.map((d, i) => <ListRow key={i} d={d} cids={ListRow_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col" data-cid="n635">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[11.525rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-md:after:right-[17.5625rem] md:max-lg:after:right-168.5" data-cid="n636" data-component="heading">
                  VFX Services
                </h4>
                {" "}
                <ul className="flex flex-col gap-3 [list-style-type:none] list-outside" data-cid="n637">
                  {ListRow2_data.map((d, i) => <ListRow2 key={i} d={d} cids={ListRow2_cids[i]} />)}
                </ul>
                {" "}
              </div>
              {" "}
              <div className="flex flex-col max-lg:items-center" data-cid="n660">
                <h4 className="block relative mb-6 pb-2 [font-family:Outfit,_sans-serif] text-lg font-extrabold leading-[1.4375rem] tracking-[0.88px] uppercase after:content-[''] after:block after:absolute after:top-[1.8125rem] after:right-[18.225rem] after:bottom-0 after:left-0 after:w-7.5 after:h-0.5 after:bg-primary after:shadow-[var(--primary)_0px_0px_5px_0px] max-lg:after:right-[5.825rem]" data-cid="n661" data-component="heading">
                  Studio Info
                </h4>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n662">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n663" />
                  {" "}
                  <span className="block" data-cid="n664">
                    No.09,Kambar Street ,
                    <br className="inline" data-cid="n665" />
                    Subramaniya Nagar,
                    <br className="inline" data-cid="n666" />
                    Tiruttani - 631209
                  </span>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n667">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n668" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n669" data-component="link" href="tel:+918925902036">
                    +91 86677586750
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n670">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] font-black leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:font-black before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n671" />
                  {" "}
                  <a className="block cursor-pointer" data-cid="n672" data-component="link" href="mailto:info@focusvfx.in">
                    creativeheadsak@gmail.com
                  </a>
                  {" "}
                </p>
                {" "}
                <p className="flex mb-4 gap-4 text-color-001 text-sm leading-[1.375rem]" data-cid="n673">
                  <i className="block mt-1 text-primary [font-family:'Font_Awesome_6_Free'] text-[0.9375rem] leading-[0.9375rem] before:content-[''] before:text-primary before:text-[0.9375rem] before:leading-[0.9375rem] max-lg:before:text-center" data-cid="n674" />
                  {" "}
                  <span className="block" data-cid="n675">
                    Mon - Sun: 09:00 AM - 10:00 PM
                  </span>
                  {" "}
                </p>
                {" "}
              </div>
              {" "}
            </div>
            {" "}
            <div className="border-t border-solid border-t-border flex pt-8 flex-wrap justify-between items-center gap-4" data-cid="n676">
              <p className="block text-color-001 text-sm leading-4" data-cid="n677">
                {"© "}
                <span className="inline" data-cid="n678" id="copyright-year">
                  2026
                </span>
                {" AJITH KUMAR. All Rights Reserved."}
              </p>
              {" "}
              <p className="block text-primary [font-family:Outfit,_sans-serif] text-sm font-extrabold leading-4.5 tracking-[1.36px] uppercase" data-cid="n679">
                THIS PAGE IS CREATED BY PMJ PROJECTS
              </p>
              {" "}
            </div>
            {" "}
          </div>
          {" "}
        </footer>
        {" "}
      </div>
    </>
  );
}
