import "./ditto.css";
import MediaCard from "./components/media-card";
import ListRow from "./components/list-row";
import ListRow2 from "./components/list-row2";
// Generated by clone-site. Do not edit by hand.
const MediaCard_data = [
  { alt: "Andhra King", id: "card-img-andhra-king-3", imgSrc: "/assets/cloned/images/e69013e6b001.jpg", title: "Andhra King", description: "A high-octane political comedy tracking the chaotic journey of a fanatic fan turned regional hero.", text: "Visual Effects", text2: "CGI Production", text3: "Compositing" },
  { alt: "Madness (Bandhal)", id: "card-img-madness-4", imgSrc: "/assets/cloned/images/comp.jpeg", title: "Madness (Bandhal)", description: "A high-octane comedy-thriller featuring Mohanlal and Dileep in a roller-coaster ride of action, suspense, and chaos.", text: "Visual Effects", text2: "CGI Production", text3: "3D Animation" },
  { alt: "Thalaivar Thambi Thalaimaiyil (TTT)", id: "card-img-ttt-5", imgSrc: "/assets/cloned/images/324f06153260.jpg", title: "Thalaivar Thambi Thalaimaiyil (TTT)", description: "A compelling political drama outlining the rebellion of rural citizens under the leadership of a charismatic town leader.", text: "Crowd Multiplication", text2: "Matte Painting", text3: "Compositing" },
  { alt: "Parasakthi", id: "card-img-parasakthi-6", imgSrc: "/assets/cloned/images/67e53db6a0b7.jpg", title: "Parasakthi", description: "A visually magnificent romance directed by Sudha Kongara, telling a story of passion, trials, and cinematic beauty.", text: "Visual Effects", text2: "Matte Painting", text3: "Compositing" },
  { alt: "Bloody Beggar", id: "card-img-bloody-beggar-7", imgSrc: "/assets/cloned/images/f33d2accbf0d.jpeg", title: "Bloody Beggar", description: "A dark comedy thriller that turns the tale of a beggar into an intense mystery.", text: "Visual Effects", text2: "Color Grading", text3: "Compositing" },
  { alt: "Ghaati", id: "card-img-ghaati-8", imgSrc: "/assets/cloned/images/05afddd9f1d4.jpeg", title: "Ghaati", description: "A rustic action drama set in a rugged landscape with breathtaking visuals.", text: "Matte Painting", text2: "Visual Effects", text3: "CGI Production" },
  { alt: "Indian 2", id: "card-img-indian-2-9", imgSrc: "/assets/cloned/images/0ae69df7bc52.jpeg", title: "Indian 2", description: "The return of Senapathy in an epic vigilante action film.", text: "De-aging", text2: "Crowd Multiplication", text3: "Visual Effects" },
  { alt: "Loveli", id: "card-img-loveli-10", imgSrc: "/assets/cloned/images/6f18599fda9f.jpeg", title: "Loveli", description: "A heart-touching romantic musical exploring the depths of modern relationships.", text: "Color Grading", text2: "Compositing", text3: "Digital Cleanup" },
  { alt: "Rathnam", id: "card-img-rathnam-11", imgSrc: "/assets/cloned/images/3df29ff21bd4.jpeg", title: "Rathnam", description: "An intense action movie packed with adrenaline-pumping sequences.", text: "Wire Removal", text2: "Blood Enhancements", text3: "Visual Effects" },
  { alt: "TK", id: "card-img-tk-12", imgSrc: "/assets/cloned/images/prep.jpg", title: "TK", description: "A gripping thriller that keeps you on the edge of your seat.", text: "Compositing", text2: "Visual Effects", text3: "Color Grading" },
  { alt: "Turbo", id: "card-img-turbo-13", imgSrc: "/assets/cloned/images/roto.jpeg", title: "Turbo", description: "A fast-paced action comedy led by Mammootty.", text: "Visual Effects", text2: "CGI Production", text3: "Compositing" },
  { alt: "Thangalaan", id: "card-img-thangalaan-14", imgSrc: "/assets/cloned/images/e750aa313d6a.jpeg", title: "Thangalaan", description: "A historical action film set against the backdrop of the Kolar Gold Fields.", text: "Environment Generation", text2: "Creature CGI", text3: "Visual Effects" },
  { alt: "Thug Life", id: "card-img-thug-life-15", imgSrc: "/assets/cloned/images/b2b66908cd9c.jfif", title: "Thug Life", description: "A highly anticipated epic action drama starring Kamal Haasan.", text: "Visual Effects", text2: "Compositing", text3: "CGI Production" },
  { alt: "Coolie", id: "card-img-coolie-16", imgSrc: "/assets/cloned/images/bdcdb38e6ebf.jpg", title: "Coolie", description: "An action extravaganza featuring high-stakes drama and massive sequences.", text: "Visual Effects", text2: "Matte Painting", text3: "Matchmove" },
  { alt: "Pushpa 2: The Rule", id: "card-img-pushpa-2-17", imgSrc: "/assets/cloned/images/09fb9509c5d4.jpg", title: "Pushpa 2: The Rule", description: "The highly anticipated sequel to Pushpa, depicting the clash of syndicates.", text: "Visual Effects", text2: "Crowd Multiplication", text3: "Compositing" }
];
const ListRow_data = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About Us" },
  { href: "/works", label: "Our Works" },
  { href: "/contact", label: "Contact Us" }
];
const ListRow2_data = [
  { label: "PREP" },
  { label: "Story Board" },
  { label: "Story Telling" },
  { label: "CGI Production" },
  { label: "Motion Graphics" },
  { label: "3D Animation" },
  { label: "Compositing" },
  { label: "ROTO" },
  { label: "Matchmovie" },
  { label: "Colour Grading" },
  { label: "Digital Cleanup" }
];
const MediaCard_cids: string[][] = [
  ["n84", "n85", "n86", "n87", "n88", "n89", "n90", "n91", "n92", "n93", "n94", "n95", "n96", "n97"],
  ["n98", "n99", "n100", "n101", "n102", "n103", "n104", "n105", "n106", "n107", "n108", "n109", "n110", "n111"],
  ["n112", "n113", "n114", "n115", "n116", "n117", "n118", "n119", "n120", "n121", "n122", "n123", "n124", "n125"],
  ["n126", "n127", "n128", "n129", "n130", "n131", "n132", "n133", "n134", "n135", "n136", "n137", "n138", "n139"],
  ["n140", "n141", "n142", "n143", "n144", "n145", "n146", "n147", "n148", "n149", "n150", "n151", "n152", "n153"],
  ["n154", "n155", "n156", "n157", "n158", "n159", "n160", "n161", "n162", "n163", "n164", "n165", "n166", "n167"],
  ["n168", "n169", "n170", "n171", "n172", "n173", "n174", "n175", "n176", "n177", "n178", "n179", "n180", "n181"],
  ["n182", "n183", "n184", "n185", "n186", "n187", "n188", "n189", "n190", "n191", "n192", "n193", "n194", "n195"],
  ["n196", "n197", "n198", "n199", "n200", "n201", "n202", "n203", "n204", "n205", "n206", "n207", "n208", "n209"],
  ["n210", "n211", "n212", "n213", "n214", "n215", "n216", "n217", "n218", "n219", "n220", "n221", "n222", "n223"],
  ["n224", "n225", "n226", "n227", "n228", "n229", "n230", "n231", "n232", "n233", "n234", "n235", "n236", "n237"],
  ["n238", "n239", "n240", "n241", "n242", "n243", "n244", "n245", "n246", "n247", "n248", "n249", "n250", "n251"],
  ["n252", "n253", "n254", "n255", "n256", "n257", "n258", "n259", "n260", "n261", "n262", "n263", "n264", "n265"],
  ["n266", "n267", "n268", "n269", "n270", "n271", "n272", "n273", "n274", "n275", "n276", "n277", "n278", "n279"],
  ["n280", "n281", "n282", "n283", "n284", "n285", "n286", "n287", "n288", "n289", "n290", "n291", "n292", "n293"]
];
const ListRow_cids: string[][] = [
  ["n325", "n326"],
  ["n327", "n328"],
  ["n329", "n330"],
  ["n331", "n332"],
  ["n333", "n334"]
];
const ListRow2_cids: string[][] = [
  ["n338", "n339"],
  ["n340", "n341"],
  ["n342", "n343"],
  ["n344", "n345"],
  ["n346", "n347"],
  ["n348", "n349"],
  ["n350", "n351"],
  ["n352", "n353"],
  ["n354", "n355"],
  ["n356", "n357"],
  ["n358", "n359"]
];

export default function Page() {
  return (
    <>
      <section className="h-170 min-h-170 flex relative pt-20 items-center overflow-hidden bg-background max-md:h-[30.45rem] max-md:min-h-[30.45rem] max-lg:pt-16 md:max-lg:h-[38.4rem] md:max-lg:min-h-[38.4rem] 2xl:h-229.5 2xl:min-h-229.5" data-cid="n22">
        <div className="h-full block absolute top-0 inset-x-0 z-0 min-w-0" data-cid="n23">
          <div className="w-320 h-170 block absolute top-0 left-0 bg-cover [background-position:50%_0%] [filter:grayscale(0.8)_brightness(0.3)_contrast(1.2)] [animation-name:bgSlowZoom] [animation-duration:12s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] [animation-direction:alternate] max-md:w-[23.4375rem] max-md:h-[30.45rem] max-lg:[background-position:50%_50%] md:max-lg:w-192 md:max-lg:h-[38.4rem] 2xl:w-480 2xl:h-229.5" style={{ backgroundImage: "url(\"/assets/cloned/images/46fe0eb562c1.jpg\")" }} data-cid="n24" />
          {" "}
          <div className="h-full block absolute top-0 inset-x-0 z-1" style={{ backgroundImage: "linear-gradient(135deg, var(--clr-6) 0%, var(--clr-12) 60%, var(--clr-2) 100%)" }} data-cid="n25" />
          {" "}
          <div className="w-125 h-125 block absolute -top-17 -left-32 z-2 opacity-[0.509976] [mix-blend-mode:screen] [filter:blur(60px)] [animation-name:volumetricPulse] [animation-duration:6s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite] pointer-events-none max-md:top-[-48.7px] max-md:left-[-37.5px] md:max-lg:-top-[3.8375rem] md:max-lg:-left-[4.8rem] 2xl:-top-[5.7375rem] 2xl:-left-48" style={{ backgroundImage: "radial-gradient(at 70% 40%, var(--clr-26) 0%, var(--clr-4) 55%)" }} data-cid="n26" />
          {" "}
          <img className="w-320 h-170 block absolute z-3 overflow-clip aspect-[auto_1280/680] pointer-events-none max-md:w-[23.4375rem] max-md:h-[30.4375rem] max-md:aspect-[auto_375/487] md:max-lg:w-192 md:max-lg:h-153.5 md:max-lg:aspect-[auto_768/614] 2xl:w-480 2xl:h-229.5 2xl:aspect-[auto_1920/918]" data-cid="n27" height="680" id="hero-particles" src="/assets/cloned/images/56ea4cef4caa.png" width="1280" alt="" />
          {" "}
        </div>
        {" "}
        <div className="block relative z-10 max-w-320 mx-auto py-16 px-8 text-left max-lg:max-w-full max-md:mx-0" data-cid="n28">
          <span className="border border-solid border-color-006 inline-block mb-6 py-[0.4rem] px-4 rounded-[50px] text-primary [font-family:Outfit,_sans-serif] text-xs font-bold leading-[0.9375rem] tracking-[3.46px] uppercase" data-cid="n29">
            FOCUS VFX STUDIO — PORTFOLIO
          </span>
          {" "}
          <h1 className="block mb-6 text-[5.625rem] font-black leading-[5.3125rem] tracking-[-1.79px] uppercase max-lg:text-5xl max-lg:leading-[2.875rem] max-lg:tracking-[-0.96px] 2xl:text-[6.5rem] 2xl:leading-[6.1875rem] 2xl:tracking-[-2.08px]" data-cid="n30" data-component="heading">
            {"OUR "}
            <span className="inline text-primary [text-shadow:var(--clr-9)_0px_0px_50px]" data-cid="n31">
              WORKS
            </span>
          </h1>
          {" "}
          <p className="border-l-[3px] border-solid border-l-primary block max-w-162.5 mb-10 pl-5 text-color-014 text-[1.1875rem] leading-[2.0625rem] max-lg:leading-[1.6875rem] max-lg:[font-size:inherit]" data-cid="n32">
            Browse through our premium cinematic projects delivered for global cinema.
          </p>
          {" "}
        </div>
        {" "}
        <div className="w-[55.5px] h-[4.6875rem] flex absolute bottom-10 left-16 z-5 min-w-0 flex-col items-center gap-3 text-color-005 [font-family:Outfit,_sans-serif] text-[0.625rem] font-bold leading-[0.8125rem] tracking-[2.6px] max-lg:hidden" data-cid="n33">
          <span className="block" data-cid="n34">
            SCROLL
          </span>
          {" "}
          <div className="w-px h-12.5 block opacity-[0.467047] [animation-name:scrollPulse] [animation-duration:2s] [animation-timing-function:ease-in-out] [animation-iteration-count:infinite]" style={{ backgroundImage: "linear-gradient(var(--color-005), var(--clr-4))" }} data-cid="n35" />
          {" "}
        </div>
        {" "}
      </section>
      <section className="block relative pt-8 pb-32 bg-background max-lg:pb-16" data-cid="n36">
        <div className="block max-w-320 px-8 max-lg:max-w-full max-lg:px-6 2xl:mx-80" data-cid="n37">
          <div className="flex mb-8 flex-wrap justify-center gap-[0.9375rem]" data-cid="n38">
            <button className="border border-solid border-primary block py-2.5 px-6 [font-family:Outfit,_sans-serif] text-lg font-bold leading-[1.4375rem] tracking-[1.76px] text-center capitalize bg-clr-27 shadow-[var(--accent)_0px_0px_15px_0px] cursor-pointer" data-cid="n39" data-component="button">
              Posters
            </button>
            <button className="border border-solid border-surface-2 block py-2.5 px-6 [font-family:Outfit,_sans-serif] text-lg font-bold leading-[1.4375rem] tracking-[1.76px] text-center capitalize cursor-pointer" data-cid="n40" data-component="button">
              Show Reels
            </button>
          </div>
          {" "}
          <div className="h-902.5 min-h-100 grid items-start gap-8 grid-cols-[repeat(auto-fit,_minmax(326px,_1fr))] grid-rows-6 max-md:h-[584.6875rem] max-md:grid-rows-18 md:max-lg:h-[305.6875rem] md:max-lg:grid-rows-9" data-cid="n41" id="works-grid">
            <div className="border border-solid border-surface block relative rounded-sm shrink-0 overflow-hidden bg-color-002 shadow-[var(--clr-2)_0px_10px_30px_0px,var(--border)_0px_0px_15px_0px] cursor-pointer" data-cid="n42">
              <div className="block relative overflow-hidden aspect-[2/3]" data-cid="n43">
                <img className="w-95.5 h-[35.8125rem] block relative z-1 max-w-full overflow-clip object-cover transform-[matrix(1.15,0,0,1.15,0,0)] origin-[191px_286.5px] max-md:w-[20.3125rem] max-md:h-122 max-md:transform-[matrix(1.1001,0,0,1.1001,0,0)] max-md:origin-[162.5px_243.75px] md:max-lg:w-85.5 md:max-lg:h-[32.0625rem] md:max-lg:transform-[matrix(1.092,0,0,1.092,0,0)] md:max-lg:origin-[171px_256.5px]" data-cid="n44" data-component="image" alt="Sumathi Valavu" id="card-img-sumathi-valavu-0" src="/assets/cloned/images/592a2a943236.jpg" />
                {" "}
                <div className="w-95.5 h-[35.8125rem] flex absolute top-0 left-0 z-2 opacity-0 p-6 flex-col justify-end" style={{ backgroundImage: "linear-gradient(to top, var(--clr-14) 0%, var(--clr-15) 40%, var(--clr-4) 100%)" }} data-cid="n45">
                  <span className="block mb-1 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.8px] uppercase" data-cid="n46">
                    Posters
                  </span>
                  {" "}
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-xl font-extrabold leading-6 tracking-[-0.4px] uppercase" data-cid="n47" data-component="heading">
                    Sumathi Valavu
                  </h3>
                  {" "}
                  <p className="block opacity-0 mb-4 text-color-014 text-[0.8125rem] leading-[1.125rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n48">
                    An eerie mystery unfolding around a notorious hairpin curve, where unexplained events force a group of investigators to uncover a dark paranormal history.
                  </p>
                  {" "}
                  <div className="h-[1.3375rem] flex opacity-0 flex-wrap gap-[0.4rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n49">
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n50">
                      Visual Effects
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n51">
                      Compositing
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n52">
                      ROTO
                    </span>
                    {" "}
                  </div>
                  {" "}
                  <div className="h-4 flex opacity-0 mt-4 items-center gap-2 text-primary [font-family:Outfit,_sans-serif] text-[0.8125rem] font-semibold leading-4 tracking-[1.28px] uppercase transform-[matrix(1,0,0,1,0,10)]" data-cid="n53">
                    <span className="block" data-cid="n54">
                      View Project
                    </span>
                    {" "}
                    <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-primary before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n55" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            <div className="border border-solid border-surface block relative rounded-sm shrink-0 overflow-hidden bg-color-002 shadow-[var(--clr-2)_0px_10px_30px_0px,var(--border)_0px_0px_15px_0px] cursor-pointer" data-cid="n56">
              <div className="block relative overflow-hidden aspect-[2/3]" data-cid="n57">
                <img className="w-95.5 h-[35.8125rem] block relative z-1 max-w-full overflow-clip object-cover transform-[matrix(1.15,0,0,1.15,0,0)] origin-[191px_286.5px] max-md:w-[20.3125rem] max-md:h-122 max-md:origin-[162.5px_243.75px] md:max-lg:w-85.5 md:max-lg:h-[32.0625rem] md:max-lg:transform-[matrix(1.092,0,0,1.092,0,0)] md:max-lg:origin-[171px_256.5px]" data-cid="n58" data-component="image" alt="Karuppu" id="card-img-karuppu-1" src="/assets/cloned/images/58cd37376202.jpg" />
                {" "}
                <div className="w-95.5 h-[35.8125rem] flex absolute top-0 left-0 z-2 opacity-0 p-6 flex-col justify-end" style={{ backgroundImage: "linear-gradient(to top, var(--clr-14) 0%, var(--clr-15) 40%, var(--clr-4) 100%)" }} data-cid="n59">
                  <span className="block mb-1 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.8px] uppercase" data-cid="n60">
                    Posters
                  </span>
                  {" "}
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-xl font-extrabold leading-6 tracking-[-0.4px] uppercase" data-cid="n61" data-component="heading">
                    Karuppu
                  </h3>
                  {" "}
                  <p className="block opacity-0 mb-4 text-color-014 text-[0.8125rem] leading-[1.125rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n62">
                    An intense cinematic saga charting the rise and redemption of a historic warrior in Tamil Nadu.
                  </p>
                  {" "}
                  <div className="h-[1.3375rem] flex opacity-0 flex-wrap gap-[0.4rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n63">
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n64">
                      Visual Effects
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n65">
                      CGI Production
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n66">
                      Matte Painting
                    </span>
                    {" "}
                  </div>
                  {" "}
                  <div className="h-4 flex opacity-0 mt-4 items-center gap-2 text-primary [font-family:Outfit,_sans-serif] text-[0.8125rem] font-semibold leading-4 tracking-[1.28px] uppercase transform-[matrix(1,0,0,1,0,10)]" data-cid="n67">
                    <span className="block" data-cid="n68">
                      View Project
                    </span>
                    {" "}
                    <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-primary before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n69" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            <div className="border border-solid border-surface block relative rounded-sm shrink-0 overflow-hidden bg-color-002 shadow-[var(--clr-2)_0px_10px_30px_0px,var(--border)_0px_0px_15px_0px] cursor-pointer" data-cid="n70">
              <div className="block relative overflow-hidden aspect-[2/3]" data-cid="n71">
                <img className="w-95.5 h-[35.8125rem] block relative z-1 max-w-full overflow-clip object-cover transform-[matrix(1.15,0,0,1.15,0,0)] origin-[191px_286.5px] max-md:w-[20.3125rem] max-md:h-122 max-md:origin-[162.5px_243.75px] md:max-lg:w-85.5 md:max-lg:h-[32.0625rem] md:max-lg:origin-[171px_256.5px]" data-cid="n72" data-component="image" alt="Jockey (1920 Madurai)" id="card-img-jockey-2" src="/assets/cloned/images/49eaabbfe89a.jpg" />
                {" "}
                <div className="w-95.5 h-[35.8125rem] flex absolute top-0 left-0 z-2 opacity-0 p-6 flex-col justify-end" style={{ backgroundImage: "linear-gradient(to top, var(--clr-14) 0%, var(--clr-15) 40%, var(--clr-4) 100%)" }} data-cid="n73">
                  <span className="block mb-1 text-primary [font-family:Outfit,_sans-serif] text-xs font-extrabold leading-[0.9375rem] tracking-[1.8px] uppercase" data-cid="n74">
                    Posters
                  </span>
                  {" "}
                  <h3 className="block mb-2 [font-family:Outfit,_sans-serif] text-xl font-extrabold leading-6 tracking-[-0.4px] uppercase" data-cid="n75" data-component="heading">
                    Jockey (1920 Madurai)
                  </h3>
                  {" "}
                  <p className="block opacity-0 mb-4 text-color-014 text-[0.8125rem] leading-[1.125rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n76">
                    Set in 1920s Madurai, a gripping tale of rival fighters and horse jockey subculture in colonial South India.
                  </p>
                  {" "}
                  <div className="h-[1.3375rem] flex opacity-0 flex-wrap gap-[0.4rem] transform-[matrix(1,0,0,1,0,15)]" data-cid="n77">
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n78">
                      Visual Effects
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n79">
                      Crowd Multiplication
                    </span>
                    <span className="border border-solid border-accent block py-[0.2rem] px-2 rounded-xs text-[0.625rem] leading-[0.8125rem] bg-color-003" data-cid="n80">
                      3D Asset Modeling
                    </span>
                    {" "}
                  </div>
                  {" "}
                  <div className="h-4 flex opacity-0 mt-4 items-center gap-2 text-primary [font-family:Outfit,_sans-serif] text-[0.8125rem] font-semibold leading-4 tracking-[1.28px] uppercase transform-[matrix(1,0,0,1,0,10)]" data-cid="n81">
                    <span className="block" data-cid="n82">
                      View Project
                    </span>
                    {" "}
                    <i className="block [font-family:'Font_Awesome_6_Free'] font-black leading-[0.8125rem] before:content-[''] before:text-primary before:text-[0.8125rem] before:font-black before:leading-[0.8125rem] before:tracking-[1.28px]" data-cid="n83" />
                    {" "}
                  </div>
                  {" "}
                </div>
                {" "}
              </div>
              {" "}
            </div>
            {MediaCard_data.map((d, i) => <MediaCard key={i} d={d} cids={MediaCard_cids[i]} />)}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      <section className="border-t border-solid border-t-border border-b border-b-border block relative py-32 bg-color-002 max-lg:py-16" data-cid="n294" id="cta">
        <div className="border border-solid border-border block relative max-w-225 my-12 mx-auto py-20 px-12 rounded-[20px] overflow-hidden text-center shadow-[var(--clr-15)_0px_30px_60px_0px] max-lg:px-6 max-lg:py-0" style={{ backgroundImage: "linear-gradient(135deg, var(--clr-36), var(--clr-37))" }} data-cid="n295">
          <div className="w-100 h-100 block absolute top-[clamp(127.6px,_50%,_calc(100%_-_127.6px))] left-[clamp(186.5px,_50%,_calc(100%_-_186.5px))] transform-[matrix(1,0,0,1,-200,-200)] pointer-events-none" style={{ backgroundImage: "radial-gradient(circle, var(--clr-38) 0%, var(--clr-39) 70%)" }} data-cid="n296" />
          {" "}
          <h2 className="block mb-6 [font-family:Outfit,_sans-serif] text-[2.5rem] font-black leading-12.5 tracking-[1px] uppercase" data-cid="n297" data-component="heading">
            HAVE A PROJECT IN MIND?
          </h2>
          {" "}
          <p className="block max-w-162.5 mb-10 mx-auto px-4 text-color-001 text-lg leading-[2.0625rem]" data-cid="n298">
            Whether it's a feature film VFX pipeline, a commercial ad CGI set extension, or motion graphics branding, let's build visual wonders together.
          </p>
          {" "}
          <div className="flex flex-wrap justify-center gap-6 max-lg:flex-col" data-cid="n299">
            <a className="h-[2.5625rem] border border-solid border-clr-4 flex relative z-1 py-3 px-8 rounded-[50px] justify-center items-center overflow-hidden text-background text-[0.8125rem] font-bold leading-[0.9375rem] tracking-[1.28px] uppercase bg-primary shadow-[var(--clr-10)_0px_0px_20px_0px] cursor-pointer" data-cid="n300" data-component="button" href="/contact">
              Discuss Project
            </a>
            {" "}
          </div>
          {" "}
        </div>
        {" "}
      </section>
      
    </>
  );
}
